huntabyte/bits-ui

.changeset/fair-laws-flow.md, src/lib/primitives/button/components/Button.svelte
=> [Button] Remove default role

.changeset/cool-dryers-glow.md, package.json, pnpm-lock.yaml, src/components/demos/menubar-demo.svelte, src/components/ui/menubar/menubar-item.svelte
=> upgrade melt for select portal bug fix

.changeset/seven-experts-juggle.md, package.json, pnpm-lock.yaml
Fixes a bug where the dialog portal div wasn't being cleaned up properly.
=> Update Melt UI version for dialog bug fixes

.changeset/quick-coins-sip.md, package.json, pnpm-lock.yaml
Update Melt UI for a menubar trigger toggle bug fix
=> update melt for menubar trigger toggle bug fix

content/getting-started.md
=> typo correction

src/components/icons/index.ts, src/components/icons/square-half.svelte, src/components/navigation/index.ts, src/components/navigation/mobile-link.svelte, src/components/navigation/mobile-nav.svelte, src/components/site-header.svelte
Hi, I wanted to add the mobile navigation to help mobile users. I just copied the design of **Formsnap**.
=> docs: add mobile navigation

src/components/index.ts, src/components/metadata.svelte, src/config/site.ts, src/routes/+layout.svelte
Just added metatags for the title, description and keywords...
=> feat: add basic metadata infos

content/delegation.md
I think this was a typo, let me know if I missed something
=> feat: fix incorrect function name in render delegation docs

.changeset/rude-panthers-cough.md, src/lib/bits/context-menu/components/ContextMenuCheckboxItem.svelte, src/lib/bits/context-menu/components/ContextMenuRadioGroup.svelte, src/lib/bits/dropdown-menu/components/DropdownMenuCheckboxItem.svelte, src/lib/bits/dropdown-menu/components/DropdownMenuRadioGroup.svelte, src/lib/bits/menubar/components/MenubarCheckboxItem.svelte, src/lib/bits/menubar/components/MenubarRadioGroup.svelte
=> fix: menu `onChange` functions

.changeset/metal-coins-occur.md, src/lib/bits/select/_types.ts, src/lib/bits/select/components/select.svelte, src/lib/bits/select/types.ts, src/tests/select/Select.spec.ts, src/tests/select/SelectTest.svelte
Fix issue with generics and type inference for `Select` component.
=> fix: select types

.changeset/nervous-birds-beg.md, src/lib/bits/calendar/components/calendar.svelte, src/lib/bits/date-picker/components/date-picker-calendar.svelte, src/lib/bits/date-picker/components/date-picker.svelte, src/lib/bits/date-range-picker/components/date-range-picker-calendar.svelte, src/lib/bits/date-range-picker/components/date-range-picker.svelte, src/lib/bits/range-calendar/components/range-calendar.svelte
Add `numberOfMonths` prop to range calendar
=> fix: calendar `months` type & range `numberOfMonths` prop

src/components/light-switch.svelte, src/components/navigation/sidebar-nav-items.svelte, src/components/navigation/sidebar-nav-main-items.svelte, src/components/navigation/sidebar-nav.svelte, src/components/site-header.svelte
Header and sidebar design changes.
=> Docs Design fixes

src/components/api-ref/data-attr-value-content.svelte, src/components/navigation/sidebar-nav-items.svelte, src/components/navigation/sidebar-nav-main-items.svelte, src/components/page-header/page-header-description.svelte, src/components/site-header.svelte, src/config/navigation.ts, src/routes/+layout.svelte, src/styles/app.postcss, src/styles/markdown.postcss
Menu labels (new), lead text balance, spacing and sizes of layout elements
=> docs: small UI changes

src/components/demos/date-field-demo.svelte, src/components/demos/date-picker-demo.svelte, src/components/demos/date-range-field-demo.svelte, src/components/demos/date-range-picker-demo.svelte
date field, date picker, date range field, date range picker
=> docs: diff placeholder colors for date fields

.changeset/seven-jobs-refuse.md, src/lib/types.ts
Add missing type exports for the Combobox component
=> fix: export Combobox types

src/components/demos/pin-input-demo.svelte, src/components/icons/index.ts
Make the design more universal
=> chore: Pin demo redesign

.changeset/proud-queens-joke.md, package.json, pnpm-lock.yaml, src/components/demos/radio-group-demo.svelte
Updates Melt UI to [v0.74.4](https://github.com/melt-ui/melt-ui/releases/tag/v0.74.4).
Closes: #359 #337
=> chore: update Melt UI

.changeset/tall-rivers-destroy.md, src/lib/bits/menu/components/menu-radio-group.svelte
=> fix: Menu Radio Group change function conditional

src/components/copy-code-button.svelte, src/components/markdown/h2.svelte, src/components/page-header/page-header-description.svelte, src/components/page-header/page-header-heading.svelte, src/styles/app.postcss
- add Inter import
- details related to font change
=> docs: add Inter font

.changeset/angry-beds-chew.md, .changeset/smooth-dancers-roll.md, content/components/scroll-area.md, package.json, pnpm-lock.yaml, src/components/demos/index.ts, src/components/demos/scroll-area-demo.svelte, src/config/navigation.ts, src/content/api-reference/index.ts, src/content/api-reference/scroll-area.ts, src/lib/bits/index.ts, src/lib/bits/popover/components/popover-trigger.svelte, src/lib/bits/scroll-area/_export.types.ts, src/lib/bits/scroll-area/_types.ts, src/lib/bits/scroll-area/components/scroll-area-content.svelte, src/lib/bits/scroll-area/components/scroll-area-corner.svelte, src/lib/bits/scroll-area/components/scroll-area-scrollbar-x.svelte, src/lib/bits/scroll-area/components/scroll-area-scrollbar-y.svelte, src/lib/bits/scroll-area/components/scroll-area-thumb-x.svelte, src/lib/bits/scroll-area/components/scroll-area-thumb-y.svelte, src/lib/bits/scroll-area/components/scroll-area-viewport.svelte, src/lib/bits/scroll-area/components/scroll-area.svelte, src/lib/bits/scroll-area/ctx.ts, src/lib/bits/scroll-area/index.ts, src/lib/bits/scroll-area/types.ts, src/lib/types.ts, svelte.config.js
This PR adds the Scroll Area component.
=> feat: Scroll Area

.changeset/lazy-tomatoes-try.md, svelte.config.js
=> fix: import path aliases

src/components/demos/scroll-area-demo.svelte, src/config/navigation.ts
=> docs: Scroll Area demo design

.changeset/silver-dolls-develop.md, src/lib/bits/button/_types.ts
=> fix: Button Prop types

.changeset/wild-snails-beam.md, package.json, pnpm-lock.yaml, src/tests/date-field/DateField.spec.ts
See: https://github.com/melt-ui/melt-ui/releases/tag/v0.76.0
=> chore: update Melt UI to v0.76.0

.changeset/flat-chefs-switch.md, src/lib/bits/menu/components/menu-checkbox-item.svelte, src/lib/bits/menu/components/menu-item.svelte, src/lib/bits/menu/components/menu-radio-item.svelte, src/lib/bits/menu/components/menu-sub-trigger.svelte, src/lib/bits/menu/types.ts
This includes all components with events inheriting from `ItemEvents` type.
Adresses #254 .
=> Forward `pointerenter` events on Menu items

content/introduction.md
It's in the small things :)
Just a couple tiny grammar fixes to the docs intro.
=> fix: small grammar fixes

.changeset/nine-feet-argue.md, package.json, pnpm-lock.yaml
=> chore: update melt to v0.76.2

.changeset/sixty-files-chew.md, src/lib/bits/context-menu/components/context-menu.svelte
=> fix: context menu closeOnItemClick

.changeset/witty-buckets-lay.md, packages/bits-ui/CHANGELOG.md, packages/bits-ui/package.json
=> Revert "Version Packages"

.changeset/brown-rats-shave.md, packages/bits-ui/src/lib/bits/button/components/button.svelte
As discussed in https://github.com/huntabyte/shadcn-svelte/discussions/418
=> Fix binding button element

packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts, packages/bits-ui/src/lib/bits/date-range-field/types.ts, packages/bits-ui/src/lib/shared/date/field/helpers.ts, packages/bits-ui/src/tests/accordion/Accordion.spec.ts, packages/bits-ui/src/tests/date-field/DateField.spec.ts, packages/bits-ui/src/tests/utils.ts, sites/docs/src/lib/components/demos/date-field-demo.svelte
The internals of this component needs a good @AdrianGonz97 sweeping
=> next: Date Field Improvements

.github/workflows/build-preview.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-prod.yml, .github/workflows/release.yml
Draft until changes are added upstream.
=> chore: Update deployment scripts

.changeset/unlucky-lemons-pump.md, packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker.svelte
=> fix: add missing props for `DateRangePicker`

.changeset/itchy-dingos-sin.md, packages/bits-ui/src/lib/bits/accordion/components/accordion-content.svelte, packages/bits-ui/src/lib/bits/accordion/components/accordion-item.svelte, packages/bits-ui/src/lib/bits/accordion/components/accordion-trigger.svelte, packages/bits-ui/src/lib/bits/accordion/ctx.ts
=> fix: Accordion item disabled reactivity

sites/docs/content/components/accordion.md, sites/docs/content/components/calendar.md, sites/docs/content/components/date-field.md, sites/docs/content/components/popover.md, sites/docs/content/delegation.md, sites/docs/content/ref.md, sites/docs/content/styling.md, sites/docs/content/type-helpers/without-children.md, sites/docs/content/utilities/merge-props.md
Was trying to read through all the docs and submit clean-up P.R's for such cases.
Draft until I can identify several rather than a P.R/fix, but if you wish to merge right away, no worries.
=> next: some docs clean-up

.changeset/clever-suns-reflect.md, packages/bits-ui/src/lib/bits/menu/components/menu-sub-content.svelte, packages/bits-ui/src/lib/bits/menu/menu.svelte.ts, packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer.svelte, packages/bits-ui/src/lib/bits/utilities/scroll-lock/scroll-lock.svelte, pnpm-lock.yaml
=> next: fix pointer event restoration

.changeset/lucky-chefs-learn.md, packages/bits-ui/src/lib/bits/command/command.svelte.ts, packages/bits-ui/src/lib/bits/command/components/command-item.svelte
=> next: fix command scrollintoview issues

packages/bits-ui/CHANGELOG.md
Co-authored-by: Hunter Johnston <64506580+huntabyte@users.noreply.github.com>
Co-authored-by: Hunter Johnston <johnstonhuntera@gmail.com>
=> next: resolve merge conflicts with main

.changeset/cool-readers-camp.md, packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte, packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer.svelte, packages/bits-ui/src/lib/internal/use-body-scroll-lock.svelte.ts
=> fix: body scroll lock issues

sites/docs/src/lib/config/navigation.ts
Change icons in the main side menu
=> main nav icon change

.changeset/thick-ligers-wonder.md, packages/bits-ui/src/lib/bits/button/components/button.svelte
=> next: make `ref` bindable for `<Button />` 

.changeset/brown-pillows-hear.md, .changeset/famous-trains-notice.md, package.json, packages/bits-ui/package.json, packages/bits-ui/src/lib/bits/combobox/components/combobox-trigger.svelte, packages/bits-ui/src/lib/bits/radio-group/radio-group.svelte.ts, packages/bits-ui/src/lib/bits/select/components/select-trigger.svelte, packages/bits-ui/src/lib/bits/toggle-group/toggle-group.svelte.ts, packages/bits-ui/src/lib/bits/toolbar/toolbar.svelte.ts, packages/tests/package.json, pnpm-lock.yaml, sites/docs/package.json
=> next: fix derived updates

sites/docs/src/lib/components/demo-code-tabs.svelte, sites/docs/src/lib/components/navigation/sidebar-nav-items.svelte, sites/docs/src/lib/components/search.svelte, sites/docs/src/lib/components/site-header.svelte, sites/docs/src/lib/config/navigation.ts
-move and restyle searchbar in header
-smaller spacing between header icons
-code tabs text and border color change
=> next(docs-style): Header search styling

.changeset/six-toys-sit.md, packages/bits-ui/src/lib/bits/combobox/components/combobox.svelte, packages/bits-ui/src/lib/bits/select/components/select.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/bits-ui/src/lib/bits/select/types.ts, packages/tests/src/tests/combobox/combobox.test.ts, packages/tests/src/tests/select/select.test.ts, sites/docs/src/lib/components/demos/combobox-demo.svelte, sites/docs/src/lib/content/api-reference/combobox.api.ts, sites/docs/src/lib/content/api-reference/select.api.ts
=> next: add `allowDeselect` prop to `Combobox` and `Select`

.changeset/tidy-rabbits-tell.md, packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts, packages/bits-ui/src/lib/bits/dialog/types.ts, packages/bits-ui/src/lib/bits/utilities/focus-scope/useFocusScope.svelte.ts, packages/bits-ui/src/lib/bits/utilities/popper-layer/types.ts, packages/bits-ui/src/lib/bits/utilities/scroll-lock/index.ts, packages/bits-ui/src/lib/bits/utilities/scroll-lock/scroll-lock.svelte, packages/bits-ui/src/lib/internal/should-trap-focus.ts, packages/bits-ui/src/lib/internal/use-body-scroll-lock.svelte.ts, sites/docs/src/lib/components/demos/dialog-demo.svelte, sites/docs/src/lib/content/api-reference/alert-dialog.api.ts, sites/docs/src/lib/content/api-reference/dialog.api.ts, sites/docs/src/lib/content/api-reference/extended-types/dialog/dialog-content-children-snippet-props.md, sites/docs/src/lib/content/api-reference/extended-types/dialog/dialog-overlay-children-snippet-props.md, sites/docs/src/lib/content/api-reference/extended-types/dialog/index.ts, sites/docs/src/lib/content/api-reference/helpers.ts
Closes #811
Closes #800 
Still have some issues when attempting to do the same in the various floating/popper components, so will address those in a separate PR.
=> fix: dialog child transitions

.changeset/modern-turkeys-carry.md, packages/bits-ui/package.json, pnpm-lock.yaml
Closes #839 
No clue what happened in esm-env 1.1.1 but updated the deps to be ^1.1.2
=> next: update esm-env

sites/docs/content/components/command.md, sites/docs/content/components/navigation-menu.md, sites/docs/content/components/pin-input.md, sites/docs/content/figma-file.md, sites/docs/src/lib/config/navigation.ts
Add figma file page to navigation
=> next: figma file

.changeset/selfish-boxes-cheat.md, packages/bits-ui/src/lib/bits/range-calendar/components/range-calendar.svelte, packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts
=> fix: `RangeCalendar` external value updates

.changeset/green-hounds-cheer.md, packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts
=> fix: pagination page aria-label

.changeset/warm-pillows-sip.md, packages/bits-ui/src/lib/bits/select/select.svelte.ts
=> fix: add role="option" to select items

.changeset/ten-shoes-shop.md, packages/bits-ui/src/lib/bits/select/components/select-content.svelte, packages/bits-ui/src/lib/bits/utilities/dismissible-layer/useDismissibleLayer.svelte.ts, packages/bits-ui/src/lib/bits/utilities/presence-layer/usePresence.svelte.ts, sites/docs/src/routes/(main)/sink/+page.svelte
=> fix: issue with nested outside clicks

.changeset/five-olives-promise.md, packages/bits-ui/src/lib/bits/tooltip/tooltip.svelte.ts
=> fix: tooltip provider -> tooltip root props

.changeset/many-clouds-begin.md, packages/bits-ui/src/lib/bits/link-preview/components/link-preview-content.svelte, packages/bits-ui/src/lib/bits/link-preview/link-preview.svelte.ts, packages/bits-ui/src/lib/internal/use-grace-area.svelte.ts, sites/docs/src/routes/(main)/sink/+page.svelte
=> fix: link preview timer issue

sites/docs/src/lib/components/search.svelte, sites/docs/src/lib/components/ui/alert/index.ts
Change dark mode colors in Callouts and search input in header
=> next: docs notes dark

.changeset/long-spiders-trade.md, packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts, sites/docs/src/lib/components/demos/pagination-demo.svelte
=> next: fix pagination 0 count

.changeset/fast-buttons-cough.md, packages/bits-ui/src/lib/internal/use-body-scroll-lock.svelte.ts, sites/docs/src/lib/components/demos/dialog-demo.svelte
=> fix: nested scroll prevention issue

.changeset/fresh-bees-hammer.md, packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts
=> fix: pagination prev/next buttons

.changeset/green-drinks-sell.md, packages/bits-ui/src/lib/bits/select/components/select-item.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts, pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/routes/(main)/sink/+page.svelte
Provides support for debounce, etc.
Closes #903
=> fix: Combobox/Select item registration

.changeset/proud-snakes-occur.md, packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts, packages/bits-ui/src/lib/bits/checkbox/components/checkbox.svelte
=> fix: allow overriding checkbox type

.changeset/sixty-panthers-fetch.md, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts, sites/docs/package.json, sites/docs/src/lib/components/ui/sheet/index.ts, sites/docs/src/lib/components/ui/sheet/sheet-content.svelte
=> fix: dialog buttons not responding on certain mobile platforms

.changeset/wise-apples-eat.md, packages/bits-ui/src/lib/bits/radio-group/components/radio-group.svelte
=> next: fix radio group `onValueChange` loop

.changeset/real-berries-jog.md, packages/bits-ui/src/lib/bits/tabs/tabs.svelte.ts, packages/tests/src/tests/tabs/tabs.test.ts
=> fix: active `Tabs.Trigger` should have default `tabindex=0`

.changeset/brave-tomatoes-dream.md
=> fix: dropdown menu trigger button type

.github/workflows/build-preview.yml, .github/workflows/ci.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-prod.yml, .github/workflows/preview-release.yml, .github/workflows/release.yml, .github/workflows/reproduire-close.yml, .github/workflows/reproduire.yml
=> chore: speed up ci

.changeset/young-actors-wave.md, packages/bits-ui/src/lib/bits/combobox/components/combobox.svelte, packages/bits-ui/src/lib/bits/select/components/select.svelte, packages/tests/src/tests/combobox/combobox-multi-test.svelte, packages/tests/src/tests/combobox/combobox.test.ts, packages/tests/src/tests/select/select-multi-test.svelte, packages/tests/src/tests/select/select.test.ts
=> fix: `Select`/`Combobox` `type="multiple"` FormData

.changeset/small-bananas-sneeze.md, packages/bits-ui/src/lib/bits/date-picker/components/date-picker.svelte, packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker.svelte
=> fix: make Date [Range] Picker `open` prop `bindable` 

.changeset/heavy-boats-drive.md, packages/bits-ui/src/lib/bits/utilities/floating-layer/useFloatingLayer.svelte.ts
=> fix: `avoidCollisions`

.changeset/light-emus-nail.md, packages/bits-ui/src/lib/bits/accordion/accordion.svelte.ts, packages/bits-ui/src/lib/bits/avatar/avatar.svelte.ts, packages/bits-ui/src/lib/bits/calendar/calendar.svelte.ts, packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts, packages/bits-ui/src/lib/bits/collapsible/collapsible.svelte.ts, packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts, packages/bits-ui/src/lib/bits/date-range-field/date-range-field.svelte.ts, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts, packages/bits-ui/src/lib/bits/label/label.svelte.ts, packages/bits-ui/src/lib/bits/link-preview/link-preview.svelte.ts, packages/bits-ui/src/lib/bits/menu/menu.svelte.ts, packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts, packages/bits-ui/src/lib/bits/navigation-menu/navigation-menu.svelte.ts, packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts, packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts, packages/bits-ui/src/lib/bits/popover/popover.svelte.ts, packages/bits-ui/src/lib/bits/radio-group/radio-group.svelte.ts, packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts, packages/bits-ui/src/lib/bits/scroll-area/scroll-area.svelte.ts, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/bits-ui/src/lib/bits/slider/slider.svelte.ts, packages/bits-ui/src/lib/bits/switch/switch.svelte.ts, packages/bits-ui/src/lib/bits/tabs/tabs.svelte.ts, packages/bits-ui/src/lib/bits/toggle-group/toggle-group.svelte.ts, packages/bits-ui/src/lib/bits/toggle/toggle.svelte.ts, packages/bits-ui/src/lib/bits/toolbar/toolbar.svelte.ts, packages/bits-ui/src/lib/internal/types.ts
Go from 100% arrow functions in the classes to selective arrow functions and `bind(this)`  for the event handlers.
=> perf: optimize classes

.changeset/angry-panthers-hope.md, packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts, packages/tests/src/tests/date-field/date-field-test.svelte, packages/tests/src/tests/date-field/date-field.test.ts
=> fix: allow resetting `DateField` value

.changeset/six-dodos-visit.md, packages/bits-ui/src/lib/bits/popover/components/popover-content-static.svelte, packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte, packages/bits-ui/src/lib/bits/popover/popover.svelte.ts
=> fix: popover trigger close detection

.changeset/thick-snakes-relate.md, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
=> fix: dialog trigger disabled prop pass through

.changeset/tame-lizards-deny.md, packages/bits-ui/src/lib/bits/select/components/select.svelte, packages/tests/src/tests/select/select.test.ts, sites/docs/src/lib/content/api-reference/select.api.ts
Related: https://github.com/huntabyte/shadcn-svelte/issues/1622
=> fix: set allowDeselect default value to false

.changeset/lucky-ads-battle.md, packages/bits-ui/src/lib/app.d.ts, packages/bits-ui/src/lib/internal/use-body-scroll-lock.svelte.ts
=> fix: SSR issue with default `open` and `disabled` Portals

.changeset/gorgeous-rice-draw.md, packages/bits-ui/package.json, packages/bits-ui/src/lib/app.d.ts, packages/bits-ui/src/lib/bits/select/components/select-scroll-down-button.svelte, packages/bits-ui/src/lib/bits/select/components/select-scroll-up-button.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/bits-ui/src/lib/bits/utilities/floating-layer/components/floating-layer-content.svelte, packages/bits-ui/src/lib/bits/utilities/floating-layer/types.ts, packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer-inner.svelte, packages/bits-ui/src/lib/internal/use-after-animations.svelte.ts, pnpm-lock.yaml
=> fix: Select/Combobox Scroll Conflicts

.changeset/smooth-clouds-happen.md, packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts, packages/bits-ui/src/lib/bits/pin-input/usePasswordManager.svelte.ts, packages/tests/src/tests/pin-input/pin-input.test.ts
=> fix: pin input paste behavior

.changeset/witty-cars-care.md, packages/bits-ui/src/lib/bits/select/components/select-item.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts
=> fix: Combobox click events firing on elements behind the content

.changeset/kind-pots-juggle.md, packages/bits-ui/src/lib/bits/combobox/components/combobox-input.svelte, packages/bits-ui/src/lib/bits/combobox/types.ts, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/tests/src/tests/combobox/combobox.test.ts, sites/docs/src/lib/content/api-reference/combobox.api.ts
=> feat: `clearOnDeselect` prop for Combobox.Input`

.changeset/hot-geese-shave.md, packages/bits-ui/src/lib/bits/select/select.svelte.ts, sites/docs/src/lib/components/demos/combobox-demo-transition.svelte, sites/docs/src/lib/components/demos/combobox-demo.svelte, sites/docs/src/lib/components/demos/dialog-demo.svelte, sites/docs/src/lib/components/demos/popover-demo-transition.svelte, sites/docs/src/lib/components/demos/popover-demo.svelte, sites/docs/src/routes/(main)/+layout.svelte
=> fix: issues with select/combobox highlighting on mobile

.changeset/tough-walls-wave.md, packages/bits-ui/src/lib/bits/tooltip/tooltip.svelte.ts
=> fix: tooltip not closing when pointer leaves

.changeset/moody-bugs-rescue.md, packages/bits-ui/src/lib/bits/utilities/focus-scope/focus-scope-stack.svelte.ts, packages/bits-ui/src/lib/bits/utilities/focus-scope/use-focus-scope.svelte.ts, packages/bits-ui/src/lib/internal/focus.ts, packages/tests/src/tests/context-menu/context-menu.test.ts
=> fix: nested focus scope infinite loops

.changeset/blue-tigers-taste.md, .changeset/brave-bottles-press.md, .changeset/brown-nails-matter.md, .changeset/eleven-candles-cheer.md, .changeset/mighty-experts-boil.md, .changeset/nasty-sloths-attack.md, docs/src/lib/content/api-reference/progress.api.ts, packages/bits-ui/src/lib/bits/progress/components/progress.svelte, packages/bits-ui/src/lib/bits/progress/progress.svelte.ts, packages/bits-ui/src/lib/bits/progress/types.ts, tests/src/tests/progress/progress.test.ts
=> fix: accessibility issues with `ProgressBar`

.changeset/bright-cooks-deliver.md, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
=> fix: Dialog focus-visible behavior

docs/content/migration-guide.md
=> docs: update migration guide

.changeset/many-ants-hang.md, packages/bits-ui/src/lib/bits/button/components/button.svelte
=> fix: Add `data-button-root` to button

.changeset/beige-monkeys-thank.md, packages/bits-ui/src/lib/bits/select/select.svelte.ts
=> fix: `Select.Trigger` toggle on touch devices

docs/src/lib/components/demos/command-demo-dialog.svelte, docs/src/lib/components/demos/command-demo.svelte, docs/src/lib/components/demos/select-demo-multiple.svelte
Closes #1234 (well, well, well, would you look at the issue number 😏 )
=> docs: update command input & select multiple-selection styles

.changeset/tricky-chicken-flash.md, packages/bits-ui/src/lib/bits/switch/switch.svelte.ts, tests/src/tests/switch/switch.test.ts
=> fix: `Switch` hidden input receiving focus

.changeset/slimy-numbers-switch.md, docs/src/lib/components/demos/checkbox-demo-group.svelte, docs/src/lib/components/navigation/index.ts, docs/src/lib/components/ui/sheet/index.ts, docs/src/routes/(main)/sink/+page.svelte, packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts, packages/bits-ui/src/lib/bits/checkbox/components/checkbox.svelte
=> fix: `Checkbox.Group` checkboxes SSR

docs/mdsx.config.js
=> docs: use clsx in examples

docs/content/components/calendar.md, docs/src/lib/components/demos/calendar-demo-presets.svelte, docs/src/lib/components/demos/calendar-demo-selects.svelte, docs/src/lib/components/demos/index.ts, docs/src/routes/(main)/sink/+page.svelte
Adds month/year select and presets examples to the Calendar docs page.
=> docs: more calendar examples

.changeset/tender-jeans-itch.md, docs/package.json, package.json, packages/bits-ui/package.json, packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts, pnpm-lock.yaml, tests/package.json
This PR cleans up menubar content internals in preparation for: https://github.com/sveltejs/svelte/pull/15469
=> chore: cleanup menubar content internals

.changeset/healthy-panthers-thank.md, .changeset/hungry-wolves-return.md, .changeset/moody-apricots-end.md, .changeset/tame-fishes-clean.md, docs/content/policies/changelog-conventions.md, docs/src/lib/components/demos/collapsible-demo-transitions.svelte, docs/src/lib/components/demos/collapsible-demo.svelte, docs/src/lib/components/demos/select-demo.svelte, docs/src/lib/utils/docs.ts, docs/src/routes/(main)/docs/[...slug]/+page.ts, docs/velite.config.js, packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte, packages/bits-ui/src/lib/bits/command/command.svelte.ts, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts, packages/bits-ui/src/lib/bits/select/select.svelte.ts, tests/src/tests/alert-dialog/alert-dialog-test.svelte, tests/src/tests/alert-dialog/alert-dialog.test.ts, tests/src/tests/dialog/dialog-test.svelte, tests/src/tests/dialog/dialog.test.ts
This PR fixes some accessibility issues identified during user testing.
I plan to continue to improve all the components to ensure anyone can use them 😃
If you encounter any issues, please raise one so I can investigate.
=> fix: various accessibility issues

.changeset/nervous-kiwis-shout.md, packages/bits-ui/src/lib/bits/context-menu/components/context-menu-content.svelte, packages/bits-ui/src/lib/bits/context-menu/types.ts, tests/src/tests/context-menu/context-menu-test.svelte, tests/src/tests/context-menu/context-menu.test.ts
=> fix(Context Menu): ensure `onOpenAutoFocus` prop is exposed

.changeset/hip-deers-push.md, docs/src/lib/components/demos/command-demo.svelte, packages/bits-ui/src/lib/bits/command/command.svelte.ts, packages/bits-ui/src/lib/bits/command/components/command-item.svelte, packages/bits-ui/src/lib/bits/command/components/command-list.svelte, tests/src/tests/command/command-test.svelte, tests/src/tests/command/command.test.ts, tests/src/tests/command/compute-command-score.test.ts
=> fix(Command): ensure original order is properly restored 

.changeset/unlucky-trainers-worry.md, docs/src/lib/content/api-reference/menubar.api.ts, packages/bits-ui/src/lib/bits/menubar/components/menubar-menu.svelte, packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts, packages/bits-ui/src/lib/bits/menubar/types.ts, tests/src/tests/menubar/menubar-test.svelte, tests/src/tests/menubar/menubar.test.ts
I think this should be all correct but I am not sure because windows has failed me for the last time.
=> fix: Add `onOpenChange` to `<Menubar.Menu/>` and fix docs

packages/bits-ui/README.md
=> chore: update readme in packages

.changeset/hungry-seahorses-march.md, packages/bits-ui/src/lib/bits/avatar/avatar.svelte.ts, tests/src/tests/avatar/avatar.test.ts
=> fix(Avatar): invalid display style for fallback

.changeset/eleven-students-give.md, packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts, tests/src/tests/pagination/pagination-test.svelte, tests/src/tests/pagination/pagination.test.ts
=> fix(Pagination): ensure `range.start` starts at 1

docs/src/lib/content/api-reference/extended-types/tooltip/index.ts, docs/src/lib/content/api-reference/extended-types/tooltip/tooltip-state-data-attr.md, docs/src/lib/content/api-reference/tooltip.api.ts
=> docs(Tooltip): fix inaccurate data-state

docs/content/components/pagination.md
Replace `bind:pressed` with `bind:page`
=> docs:Fix pagination example

.changeset/stale-toys-promise.md, docs/src/lib/content/api-reference/combobox.api.ts, docs/src/lib/content/api-reference/date-picker.api.ts, docs/src/lib/content/api-reference/date-range-picker.api.ts, docs/src/lib/content/api-reference/helpers.ts, docs/src/lib/content/api-reference/link-preview.api.ts, docs/src/lib/content/api-reference/popover.api.ts, docs/src/lib/content/api-reference/select.api.ts, docs/src/lib/content/api-reference/tooltip.api.ts, packages/bits-ui/src/lib/bits/popover/exports.ts, packages/bits-ui/src/lib/bits/popover/types.ts
=> docs: ensure `*.Portal` subcomponents are documented

.changeset/cool-beans-eat.md, .changeset/warm-onions-kick.md, docs/content/components/combobox.md, docs/content/components/select.md, docs/src/lib/components/demos/combobox-demo-auto-scroll-delay.svelte, docs/src/lib/components/demos/index.ts, docs/src/lib/components/demos/select-demo-auto-scroll-delay.svelte, docs/src/lib/components/demos/select-demo.svelte, docs/src/lib/components/markdown/h3.svelte, docs/src/lib/content/api-reference/combobox.api.ts, docs/src/lib/content/api-reference/extended-types/select/delay-prop.md, docs/src/lib/content/api-reference/extended-types/select/index.ts, docs/src/lib/content/api-reference/select.api.ts, packages/bits-ui/src/lib/bits/select/components/select-scroll-down-button.svelte, packages/bits-ui/src/lib/bits/select/components/select-scroll-up-button.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/bits-ui/src/lib/bits/select/types.ts
Also changes the docs Select example to use cubic easing for auto scroll delay (speed up the longer the user auto-scrolls for)
=> feat(Select|Combobox): Make auto-scroll delay configurable

.changeset/smooth-cycles-applaud.md, .changeset/warm-parrots-rule.md, docs/src/lib/components/demos/select-demo.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts, packages/bits-ui/src/lib/internal/use-dom-typeahead.svelte.ts
=> fix(Select): typeahead and highlight fixes

.changeset/dirty-guests-kick.md, packages/bits-ui/src/lib/bits/accordion/components/accordion.svelte, packages/bits-ui/src/lib/bits/calendar/components/calendar.svelte, packages/bits-ui/src/lib/bits/combobox/components/combobox.svelte, packages/bits-ui/src/lib/bits/date-field/components/date-field.svelte, packages/bits-ui/src/lib/bits/date-picker/components/date-picker.svelte, packages/bits-ui/src/lib/bits/date-range-field/components/date-range-field.svelte, packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker.svelte, packages/bits-ui/src/lib/bits/range-calendar/components/range-calendar.svelte, packages/bits-ui/src/lib/bits/select/components/select.svelte, packages/bits-ui/src/lib/bits/slider/components/slider.svelte, packages/bits-ui/src/lib/bits/toggle-group/components/toggle-group.svelte, packages/bits-ui/src/lib/bits/toolbar/components/toolbar-group.svelte
=> fix: ensure default values are set if spread props reassigned

docs/src/lib/components/search.svelte
=> docs: ensure search box is always on top

.changeset/eighty-roses-carry.md, docs/src/lib/components/demos/command-demo.svelte, packages/bits-ui/src/lib/bits/command/components/command.svelte
=> fix(Command): ensure `onValueChange` only fires when the value changes

.changeset/good-swans-jump.md, .changeset/sharp-badgers-travel.md, docs/src/routes/(main)/sink/+page.svelte, packages/bits-ui/src/lib/bits/command/command.svelte.ts, packages/bits-ui/src/lib/bits/command/types.ts
=> fix(Command): list restoration after empty state

.changeset/eight-impalas-drum.md, docs/src/lib/components/navigation/sidebar-nav.svelte, docs/src/routes/(main)/sink/+page.svelte, packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts, packages/bits-ui/src/lib/bits/utilities/focus-scope/use-focus-scope.svelte.ts, packages/bits-ui/src/lib/internal/focus.ts
=> fix(Dialog): ensure conditional content doesn't break nested focus

docs/content/components/combobox.md
=> docs: fix reusable combobox example

.changeset/tall-bees-turn.md, packages/bits-ui/src/lib/bits/command/command.svelte.ts
=> fix(Command): ensure groups without headings have a fallback

.changeset/wise-shrimps-try.md, packages/bits-ui/src/lib/bits/command/command.svelte.ts
=> fix(Command): fallback to id when group has no value

.changeset/forty-parrots-agree.md, packages/bits-ui/src/lib/bits/utilities/text-selection-layer/text-selection-layer.svelte, packages/bits-ui/src/lib/bits/utilities/text-selection-layer/use-text-selection-layer.svelte.ts
=> fix(Multiple): ensure `preventOverflowTextSelection` prop is applied

.changeset/silly-months-play.md, packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts, packages/bits-ui/src/lib/bits/checkbox/components/checkbox-group.svelte, packages/bits-ui/src/lib/bits/checkbox/components/checkbox.svelte, tests/src/tests/checkbox/checkbox-group-test.svelte, tests/src/tests/checkbox/checkbox.test.ts
=> fix(Checkbox): ensure Checkbox.Group value setter is called

docs/content/components/combobox.md
=> docs(Combobox): correct scroll lock section

.changeset/breezy-bananas-explode.md, packages/bits-ui/src/lib/bits/scroll-area/scroll-area.svelte.ts
Fixes #1374 
Addresses part of : https://github.com/huntabyte/shadcn-svelte/issues/1889
=> fix(ScrollArea): ensure thumb properly restores previous position

.changeset/thick-coats-rhyme.md, packages/bits-ui/src/lib/bits/date-picker/exports.ts, packages/bits-ui/src/lib/bits/date-picker/types.ts
=> fix: export DatePicker Portal|Ports

.changeset/cyan-owls-hear.md, .changeset/large-buckets-train.md, .changeset/quiet-worms-speak.md, .changeset/red-lions-draw.md, docs/content/components/calendar.md, docs/src/lib/components/demos/calendar-demo.svelte, docs/src/lib/content/api-reference/calendar.api.ts, packages/bits-ui/src/lib/bits/calendar/calendar.svelte.ts, packages/bits-ui/src/lib/bits/calendar/components/calendar.svelte, packages/bits-ui/src/lib/bits/date-picker/components/date-picker.svelte, packages/bits-ui/src/lib/bits/date-picker/date-picker.svelte.ts, packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker.svelte, packages/bits-ui/src/lib/bits/date-range-picker/date-range-picker.svelte.ts, packages/bits-ui/src/lib/bits/range-calendar/components/range-calendar.svelte, packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts, packages/bits-ui/src/lib/internal/date-time/calendar-helpers.svelte.ts, tests/src/tests/calendar/calendar.test.ts, tests/src/tests/date-range-picker/date-range-picker.test.ts, tests/src/tests/range-calendar/range-calendar.test.ts
=> fix(Calendars): ensure `weekStartsOn` is absolute

docs/src/lib/components/homepage/card-air.svelte, docs/src/lib/components/homepage/card-toggle.svelte, docs/src/lib/components/homepage/home-select.svelte, docs/src/lib/components/homepage/home-slider.svelte, docs/src/lib/components/homepage/home-switch.svelte, docs/src/lib/components/homepage/home-toolbar.svelte, docs/src/lib/components/light-switch.svelte, docs/src/lib/config/site.ts, docs/src/lib/styles/app.css, docs/src/routes/+page.svelte
Small improvements at homepage
=> Homepage small tweaks

.changeset/breezy-tools-judge.md, .changeset/silly-foxes-join.md, packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts, tests/src/tests/date-range-field/date-range-field.test.ts
=> fix(DateField): ensure prepopulated value takes priority

packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts
Finally consolidate a lot of the shared logic to reduce the LOC and bundle size of the date field.
=> chore: cleanup date field internals

.changeset/long-mails-clap.md, docs/src/lib/components/demos/index.ts, docs/src/lib/components/demos/tooltip-demo-group.svelte, packages/bits-ui/src/lib/bits/tooltip/tooltip.svelte.ts, packages/bits-ui/src/lib/internal/use-grace-area.svelte.ts
=> fix(Tooltip): ensure only one tooltip per provider can be open

.changeset/hungry-bears-yell.md, .changeset/yellow-monkeys-tease.md, docs/src/routes/(main)/sink/+page.svelte, packages/bits-ui/src/lib/bits/select/components/select-scroll-down-button.svelte, packages/bits-ui/src/lib/bits/select/components/select-scroll-up-button.svelte, packages/bits-ui/src/lib/bits/select/select.svelte.ts
Fixes #1468 
This pull request focuses on fixing issues with scroll button rendering in the `Select` and `Combobox` components, improving the `Select` component's functionality. The most significant updates include ensuring scroll buttons render correctly on subsequent mounts, refactoring the `Select` component's state management.
=> fix(Select): ensure scroll buttons render on subsequent mounts

docs/src/routes/(docs)/+layout.svelte
This is failing lint because the PR submitted from my phone. I will deal with tomorrow.
=> docs: enable eruda under query param flag

.changeset/curly-tables-grab.md, packages/bits-ui/src/lib/bits/slider/helpers.ts, tests/src/tests/slider/slider.test.ts
=> fix(Slider): ensure floating point precision aligns with step

.changeset/tidy-badgers-feel.md, packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte, packages/bits-ui/src/lib/bits/navigation-menu/components/navigation-menu-content-impl.svelte, packages/bits-ui/src/lib/bits/scroll-area/scroll-area.svelte.ts, packages/bits-ui/src/lib/bits/slider/slider.svelte.ts, packages/bits-ui/src/lib/bits/utilities/escape-layer/escape-layer.svelte, packages/bits-ui/src/lib/bits/utilities/escape-layer/types.ts, packages/bits-ui/src/lib/bits/utilities/escape-layer/use-escape-layer.svelte.ts, packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer-inner.svelte, packages/bits-ui/src/lib/internal/use-grace-area.svelte.ts
=> fix(Slider): shadow dom support

.changeset/green-women-cover.md, packages/bits-ui/src/lib/bits/utilities/floating-layer/use-floating-layer.svelte.ts, packages/bits-ui/src/lib/internal/floating-svelte/types.ts, packages/bits-ui/src/lib/internal/floating-svelte/use-floating.svelte.ts
=> fix: floating component coordinates when anchor hidden

.changeset/thirty-deer-shout.md, packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts, tests/src/tests/checkbox/checkbox.browser.test.ts
=> fix(Checkbox): only call onValueChange once per change to group

.changeset/short-socks-look.md, packages/bits-ui/src/lib/bits/navigation-menu/navigation-menu.svelte.ts
=> fix(NavigationMenu): Ensure MenuItem ref is bindable

.changeset/yummy-clubs-camp.md, packages/bits-ui/package.json, pnpm-lock.yaml
=> chore: update deps

.changeset/polite-donuts-rule.md, packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
=> fix: dont handle prevented contextmenu events

.changeset/deep-clubs-brake.md, .github/workflows/ci.yml, package.json, packages/bits-ui/src/lib/internal/date-time/calendar-helpers.svelte.ts
=> fix(Calendar): race condition in month navigation

.changeset/hot-monkeys-build.md, packages/bits-ui/src/lib/bits/link-preview/link-preview.svelte.ts
=> fix(LinkPreview): ensure `forceMount` pointerleave works as expected

.changeset/little-rice-happen.md, packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte, packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte, packages/bits-ui/src/lib/bits/popover/components/popover-content-static.svelte, packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte, packages/bits-ui/src/lib/bits/popover/popover.svelte.ts, packages/bits-ui/src/lib/bits/utilities/focus-scope/focus-scope-manager.ts, packages/bits-ui/src/lib/bits/utilities/focus-scope/focus-scope.svelte.ts, tests/src/tests/dialog/dialog.browser.test.ts, tests/src/tests/select/select.browser.test.ts
=> fix: restore focus to element that triggered the dialog/popover

docs/content/components/alert-dialog.md
=> docs: Update Alert Dialog docs to describe the default autofocus behavior

.github/workflows/bundle-analysis.yml, .github/workflows/update-bundle-baseline.yml
Numbers don't appear to be accurate so will pause in the meantime.
=> chore: pause bundle analyzer till accurate

docs/content/components/dropdown-menu.md
Updates invalid type references in the Dropdown documentation.
=> docs: fix invalid dropdown types
