.changeset/three-camels-hug.md
src/lib/bits/context-menu/components/ContextMenuContent.svelte
src/lib/bits/dropdown-menu/components/DropdownMenuContent.svelte
src/lib/bits/select/components/SelectContent.svelte

I previously added an overlay behind the menus to indicate that you can't directly interact with something outside of the menu without unexpected side effects while the menu is open. However, this should be handled more elegantly, so I'm removing the overlay until an alternative solution is decided.

remove overlay from menus for now

---

src/app.html
src/routes/+layout.svelte

I noticed on mobile (I'm always on my phone 😄 ) an overflow on the main content. I also noticed that the logo was not used properly as a favicon in the HTML attributes.

docs: fix overflow issue with the content

---

.changeset/olive-hairs-love.md
src/lib/bits/avatar/components/AvatarImage.svelte
src/lib/bits/avatar/ctx.ts

Fix: Bug preventing avatar `src` from clearing

---

.changeset/short-tomatoes-ring.md
src/lib/bits/alert-dialog/types.ts
src/lib/bits/checkbox/types.ts
src/lib/bits/collapsible/types.ts
src/lib/bits/context-menu/types.ts
src/lib/bits/dialog/types.ts
src/lib/bits/dropdown-menu/types.ts
src/lib/bits/link-preview/types.ts
src/lib/bits/menubar/types.ts
src/lib/bits/popover/types.ts
src/lib/bits/select/types.ts
src/lib/bits/switch/types.ts
src/lib/bits/toggle/types.ts
src/lib/bits/tooltip/types.ts

This update addresses annoying type issues with some of the `onChange` functions, where the value passed could possibly be `undefined`, even if impossible. 
Some values could still possibly be undefined, such as the radio groups, etc.,  but most of them cannot.

Improve types

---

.changeset/proud-laws-jump.md
src/lib/bits/accordion/components/AccordionTrigger.svelte
src/lib/bits/alert-dialog/components/AlertDialogAction.svelte
src/lib/bits/alert-dialog/components/AlertDialogCancel.svelte
src/lib/bits/alert-dialog/components/AlertDialogTrigger.svelte
src/lib/bits/checkbox/components/Checkbox.svelte
src/lib/bits/collapsible/components/CollapsibleTrigger.svelte
src/lib/bits/dialog/components/DialogClose.svelte
src/lib/bits/dialog/components/DialogTrigger.svelte
src/lib/bits/dropdown-menu/components/DropdownMenuTrigger.svelte
src/lib/bits/menubar/components/MenubarTrigger.svelte
src/lib/bits/popover/components/PopoverClose.svelte
src/lib/bits/popover/components/PopoverTrigger.svelte
src/lib/bits/popover/types.ts
src/lib/bits/radio-group/components/RadioGroupItem.svelte
src/lib/bits/select/components/SelectTrigger.svelte
src/lib/bits/switch/components/Switch.svelte
src/lib/bits/tabs/components/TabsTrigger.svelte
src/lib/bits/tabs/types.ts
src/lib/bits/toggle/components/Toggle.svelte
src/lib/bits/tooltip/components/TooltipTrigger.svelte

Using SelectTrigger shadcn/svelte with forms causes form submit. This happens, because button by default has `type="submit"`.
I think it's good idea to set `type="button"` instead, to prevent unwanted submits.
Here's implementation which allows to change it by developer, but maybe it should not be possible to changed at all?

add type="button" to all components using button element

---

.changeset/silver-roses-yell.md
src/lib/bits/checkbox/components/Checkbox.svelte
src/tests/checkbox/Checkbox.spec.ts

[Checkbox]: Fix bug with `disabled` attribute on the button

---

.changeset/wise-plants-ring.md
src/lib/bits/alert-dialog/components/AlertDialog.svelte

[Just like `Dialog` allows setting the `openFocus` and `closeFocus` props ourselves](https://github.com/huntabyte/bits-ui/blob/main/src/lib/bits/dialog/components/Dialog.svelte#L15-L16), I think it would make sense that `AlertDialog` allow these props as well.

feat: allow setting AlertDialog openFocus & closeFocus props

---

src/lib/bits/alert-dialog/components/AlertDialog.svelte

Follow-up PR of https://github.com/huntabyte/bits-ui/pull/167, both props should also be set into the ctx [the same way it's done in the `Dialog` component](https://github.com/huntabyte/bits-ui/blob/main/src/lib/bits/dialog/components/Dialog.svelte#L29-L30).
Sorry for missing this in the original PR 🙂

fix: set AlertDialog openFocus & closeFocus props in ctx

---

.changeset/thick-guests-brush.md
src/content/api-reference/calendar.ts
src/content/api-reference/range-calendar.ts
src/lib/bits/calendar/_types.ts
src/lib/bits/calendar/components/calendar.svelte
src/lib/bits/range-calendar/_types.ts
src/lib/bits/range-calendar/components/range-calendar.svelte
src/lib/internal/focus.ts
src/lib/internal/index.ts

Adds an `initialFocus` prop to the `<Calendar />` and `<RangeCalendar />` components to automatically focus either the selected date, today's date, or the first day of the month depending on what is in the view when the calendar mounts.

feat: `initialFocus` prop for calendar components

---

.changeset/aspect-ratio-default-value.md
src/lib/bits/aspect-ratio/_types.ts
src/lib/bits/aspect-ratio/components/aspect-ratio.svelte

When not defining the AspectRatio ratio prop it will throw an error and in docs is defined as optional.
`type Props = Expand<{
ratio: number;
}>;`
In _types.ts the prop is defined as needed. Just changed it to optional.

fix: Set aspect ratio prop optional

---

src/components/copy-code-button.svelte

When you click on the button to copy code in a document website, it will contain the word "Copy".
So, instead of using sr-only to hide the text, use aria-label.

docs: Don't include the word "Copy" when clicking the Copy button

---

.changeset/kind-files-fold.md
.eslintrc.cjs
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_change.yml
.github/ISSUE_TEMPLATE/feature_request.yml
src/lib/bits/pagination/components/pagination.svelte

This PR fixes an issue where the internal stores managed by melt weren't updated when the value of the props changed after the initial load.

fix: pagination prop reactivity

---

.changeset/quick-pandas-explain.md
src/content/api-reference/select.ts
src/lib/bits/select/components/select-value.svelte

Closes: #283 
This PR adds a `data-placeholder` attribute to the `<Select.Value />` element when a label is not present (when the placeholder is showing).
This enables you to style the element differently when in the placeholder state using that attribute.

feat: `data-placeholder` attribute for `Select.Value`

---

.changeset/pink-pots-nail.md
src/content/api-reference/select.ts
src/lib/bits/select/components/select-item.svelte

Expose the `isSelected` boolean state as a slot prop to the `<Select.Item />` component. This prevents users from being forced to using `<Select.ItemIndicator />` should they not want to use that component.

feat: expose `isSelected` slot prop to `Select.Item`

---

.changeset/tall-students-sleep.md
src/lib/bits/link-preview/components/link-preview-content.svelte
src/lib/bits/menu/components/menu-content.svelte
src/lib/bits/popover/components/popover-content.svelte
src/lib/bits/popover/components/popover.svelte
src/lib/bits/popover/ctx.ts
src/lib/bits/select/components/select-content.svelte

Fixes a bug where when an `Arrow` component was used within one of the floating components, the content would shift further and further away from the trigger with each open/close.
Closes: #288

fix: floating arrow shifting content

---

src/content/api-reference/alert-dialog.ts

The docs claim Alert Dialog's closeOnOutsideClick property is true by default but it is not:
https://github.com/huntabyte/bits-ui/blob/84930bafd1a11fcd901778f7c1e7441a296219bd/src/lib/bits/alert-dialog/components/alert-dialog.svelte#L10
I assume its behaving as intended, just like the radix primitives, so this PR just fixes the typo in the docs.

docs: fix Alert Dialog closeOnOutsideClick default

---

.changeset/selfish-numbers-know.md
.changeset/stupid-lobsters-provide.md
content/components/slider.md
package.json
pnpm-lock.yaml
src/components/demos/slider-demo.svelte
src/content/api-reference/slider.ts
src/lib/bits/menu/components/menu-sub-trigger.svelte
src/lib/bits/slider/_types.ts
src/lib/bits/slider/components/slider-thumb.svelte
src/lib/bits/slider/components/slider-tick.svelte
src/lib/bits/slider/components/slider.svelte
src/tests/slider/SliderRangeTest.svelte
src/tests/slider/SliderTest.svelte

Closes #307
Closes #304 
This PR also updates Melt UI to the latest version which results in a multitude of small bug fixes regarding dialogs and menu performance. However, these updates introduce a breaking change to the `Slider` components.
The `Slider.Root` now exposes the `thumbs` and `ticks` slot props, each of which is an array of builders that must be passed to the `Slider.Thumb` and `Slider.Tick` components if being used.
```svelte
<Slider.Root let:thumbs let:ticks>
{#each thumbs as thumb}
<Slider.Thumb {thumb} />
{/each}
{#each ticks as tick}
<Slider.Tick {tick} />
{/each}
</Slider.Root>
```

fix: menubar sub bug and update Melt UI to latest

---

content/introduction.md

Noticed the link to `/docs/styling` in the Intro page was pointed at `/styling` which gave me a 404

fix(docs): link in introduction.md

---

.github/ISSUE_TEMPLATE/bug_report.yml
src/routes/repro/+page.ts

You can now easily create a reproduction by visiting https://bits-ui.com/repro

chore: add reproduction redirect

---

.changeset/funny-balloons-bathe.md
src/lib/bits/toolbar/components/toolbar-button.svelte
src/lib/bits/toolbar/components/toolbar-link.svelte
src/lib/bits/toolbar/types.ts
src/tests/toolbar/Toolbar.spec.ts
src/tests/toolbar/ToolbarTest.svelte

At present click events are not forwarded from toolbar buttons and links, making them pretty much useless except in render delegation mode.

fix: Forward click events from toolbar buttons and links

---

.changeset/clean-peas-add.md
svelte.config.js
tsconfig.json

The `@` alias that was added [here](https://github.com/huntabyte/bits-ui/pull/367/files#diff-6317e218ea40a2a9b47af98e100e81c06f9c0abff66737e6ca06ec4b29402242) was replacing all instances of `@` in the import paths, causing the built package to break when it would misfire upon seeing `@melt-ui/svelte`.

fix: Adjusted import aliases to fix the malformed package build

---

.changeset/nine-carpets-vanish.md
src/lib/helpers/event-handlers.ts

Svelte forwarded events are wrapped in a `CustomEvent` (clearly seen when logging the received event from svelte). This fixes incorrect `.detail` types and issue #389 .
`CustomEventHandler` now matches the logged output from event handlers:

fix: Wrap CustomEventHandler with CustomEvent

---

.changeset/afraid-otters-give.md
src/lib/bits/date-picker/components/date-picker.svelte

After this discussion here https://github.com/huntabyte/bits-ui/discussions/388, it turns out that the `open` prop was not being exposed, ergo, couldn't bind to it for programmatic control.
This P.R exposes it and the `onOpenChange` function.
If there's something else you wish added/removed, please let me know.
Closes: #399

chore: expose `open` and `onOpenChange` props to DatePicker component

---

.changeset/loud-icons-bake.md
src/lib/bits/menu/types.ts

Google Chrome gives PointerEvent by according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) Firefox and Safari still sends MouseEvent. PointerEvent inherits from MouseEvent and thus giving this the type of MouseEvent should be safe.
I don't know if this is Event because of Melt reasons but this seems sane. If this would warrant a changeset I'll add it, but it seems like a very small change

Change contextmenu event to MouseEvent

---

.changeset/rare-actors-shout.md
src/components/demos/combobox-demo.svelte
src/content/api-reference/combobox.ts
src/lib/bits/combobox/_types.ts
src/lib/bits/combobox/components/combobox.svelte

Closes: #397
This PR introduces a new prop to the `Combobox.Root`, `touchedInput`, which you can bind to and receive updates on whether the input has been touched or not. This enables you to do things like this:
```svelte
<script lang="ts">
import { Combobox } from "$lib/index.js";
import { flyAndScale } from "@/utils/index.js";
import { Check, OrangeSlice, CaretUpDown } from "$icons/index.js";
const fruits = [
{ value: "mango", label: "Mango" },
{ value: "watermelon", label: "Watermelon" },
{ value: "apple", label: "Apple" },
{ value: "pineapple", label: "Pineapple" },
{ value: "orange", label: "Orange" },
];
let inputValue = "";
let touchedInput = false;
$: filteredFruits =
inputValue && touchedInput
? fruits.filter((fruit) => fruit.value.includes(inputValue.toLowerCase()))
: fruits; …
```

feat: Combobox `touchedInput`

---

.changeset/fifty-stingrays-flash.md
packages/bits-ui/src/lib/bits/toolbar/components/toolbar-group.svelte
packages/bits-ui/src/tests/toolbar/Toolbar.spec.ts
pnpm-lock.yaml
sites/docs/package.json
sites/docs/src/lib/components/demos/toolbar-demo.svelte
sites/docs/svelte.config.js

fix: toolbar onValueChange firing

---

packages/bits-ui/src/lib/bits/accordion/accordion.svelte.ts
packages/bits-ui/src/lib/bits/avatar/avatar.svelte.ts
packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts
packages/bits-ui/src/lib/bits/collapsible/collapsible.svelte.ts
packages/bits-ui/src/lib/internal/context.ts

- enable using symbols as context keys
- infer attrs as const
- use private properties where possible
- use state instead of box where possible
- improve performance of `verifyContextDeps` by not calling `getAllContexts` when `verifyContextDeps` is mostly used for 1/2 contexts. use `hasContext` instead
- simplify some logic...

next: more improvements

---

packages/bits-ui/src/lib/bits/index.ts
packages/bits-ui/src/lib/bits/popover/components/popover-close.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts
packages/bits-ui/src/lib/bits/utilities/floating-layer/components/floating-layer-content.svelte
packages/bits-ui/src/lib/bits/utilities/floating-layer/floating-layer.svelte.ts
packages/bits-ui/src/lib/bits/utilities/floating-layer/types.ts
packages/bits-ui/src/lib/bits/utilities/index.ts
packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer.svelte
packages/bits-ui/src/lib/bits/utilities/portal/index.ts
packages/bits-ui/src/lib/bits/utilities/portal/portal.svelte
packages/bits-ui/src/lib/bits/utilities/portal/types.ts
packages/bits-ui/src/lib/bits/utilities/portal/use-portal.svelte.ts
packages/bits-ui/src/lib/internal/use-presence.svelte.ts
packages/bits-ui/src/lib/internal/use-size.svelte.ts
packages/bits-ui/src/lib/internal/use-state-machine.svelte.ts

next: Portal

---

.changeset/rotten-spoons-carry.md
packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-overlay.svelte
packages/bits-ui/src/lib/bits/combobox/components/combobox-arrow.svelte
packages/bits-ui/src/lib/bits/date-picker/components/date-picker-arrow.svelte
packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker-arrow.svelte
packages/bits-ui/src/lib/bits/dialog/components/dialog-overlay.svelte
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-arrow.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-arrow.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-separator.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-arrow.svelte
packages/bits-ui/src/lib/bits/select/components/select-arrow.svelte
packages/bits-ui/src/lib/bits/separator/components/separator.svelte
packages/bits-ui/src/lib/bits/slider/components/slider-range.svelte
packages/bits-ui/src/lib/bits/slider/components/slider-thumb.svelte
packages/bits-ui/src/lib/bits/slider/components/slider-tick.svelte
packages/bits-ui/src/lib/bits/switch/components/switch-thumb.svelte
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-arrow.svelte
packages/bits-ui/src/tests/combobox/ComboboxTest.svelte
packages/bits-ui/src/tests/link-preview/LinkPreviewTest.svelte
packages/bits-ui/src/tests/popover/PopoverTest.svelte
packages/bits-ui/src/tests/select/SelectTest.svelte
packages/bits-ui/src/tests/tooltip/TooltipTest.svelte

Was doing some dep cleanup for Runed and Bits was causing warnings for this in the newer versions of Svelte 5

chore: Replaced all self-closing non-void elements

---

.changeset/sixty-pens-confess.md
eslint.config.js
packages/bits-ui/src/lib/bits/button/components/button.svelte
packages/bits-ui/src/lib/bits/combobox/components/combobox-content.svelte
packages/bits-ui/src/lib/bits/combobox/components/combobox-item.svelte
packages/bits-ui/src/lib/bits/dialog/components/dialog-overlay.svelte
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-trigger.svelte
packages/bits-ui/src/lib/bits/select/components/select-content.svelte
packages/bits-ui/src/lib/bits/select/components/select-item.svelte
packages/bits-ui/src/lib/bits/toolbar/components/toolbar-link.svelte
packages/bits-ui/src/tests/alert-dialog/AlertDialogTest.svelte
packages/bits-ui/src/tests/combobox/ComboboxTest.svelte
packages/bits-ui/src/tests/context-menu/ContextMenuTest.svelte
packages/bits-ui/src/tests/dialog/DialogTest.svelte
packages/bits-ui/src/tests/dropdown-menu/DropdownMenuTest.svelte
packages/bits-ui/src/tests/select/SelectTest.svelte
sites/docs/src/lib/components/api-ref/props-table.svelte
sites/docs/src/lib/components/api-section.svelte
sites/docs/src/lib/components/component-preview.svelte
sites/docs/src/lib/components/demos/calendar-demo.svelte
sites/docs/src/lib/components/demos/date-picker-demo.svelte
sites/docs/src/lib/components/demos/date-range-field-demo.svelte
sites/docs/src/lib/components/demos/date-range-picker-demo.svelte
sites/docs/src/lib/components/demos/popover-demo.svelte
sites/docs/src/lib/components/demos/progress-demo.svelte
sites/docs/src/lib/components/demos/range-calendar-demo.svelte
sites/docs/src/lib/components/icons/switch-off.svelte
sites/docs/src/lib/components/icons/switch-on.svelte

closes #520 
- fixes the a11y warnings by updating to the new `_` format
- fixed more places where there were self-closing non-void tags
- replaced unnecessary static `svelte:element` tags
- updated eslint rules to ignore the new a11y warnings

chore: Making it more Svelte 5 compatible

---

.changeset/thick-turkeys-grab.md
packages/bits-ui/src/lib/bits/floating/_types.ts

The ContentProps type is used by the `Select` and `DropdownMenu`. I just exported the `Expand` type from `$lib/internal/index.js`
This closes #543, closes #512.

fix: ContentProps type

---

.changeset/fresh-islands-cover.md
packages/bits-ui/src/lib/bits/combobox/types.ts

Changed types since the attributes are applied to a `<label>` element and not a `<div>` element.

fix: Updated ComboboxLabelProps to use HTMLLabelAttributes

---

.changeset/clever-rockets-accept.md
packages/bits-ui/src/lib/bits/button/components/button.svelte
packages/bits-ui/src/lib/bits/button/types.ts

Forward `pointerdown`, `pointerup`, `mousedown`, and `mouseup` events from the `<Button>` component

feat: forward additional events from `<Button>`

---

packages/bits-ui/src/lib/bits/date-picker/components/date-picker.svelte
packages/bits-ui/src/lib/bits/date-range-picker/components/date-range-picker.svelte

this PR solves two issues:
- clearing value for date range field https://github.com/huntabyte/bits-ui/issues/391
- clearing value for date picker when value is set to undefined (not reported. Currently clearing value works only when is set to null, but this will cause TS error)
I still have issue with date range field which will not clear segments even when value, startValue and endValue clears (for date field it works fine). I'm not sure how segments get updates after value changes - I need some help here. Maybe it must be done on melt-ui.

fix: date pickers clear

---

sites/docs/content/components/scroll-area.md

Hi @huntabyte 👋
This PR corrects a small issue I found in the [docs](https://www.bits-ui.com/docs/components/scroll-area):
```diff
- import { ScrollArea } from "$lib/index.js";
+ import { ScrollArea } from "bits-ui";
```

docs: Update ScrollArea import

---

package.json
packages/bits-ui/package.json
packages/bits-ui/src/lib/bits/context-menu/components/context-menu-content.svelte
packages/bits-ui/src/lib/bits/context-menu/components/context-menu-trigger.svelte
packages/bits-ui/src/lib/bits/dropdown-menu/components/dropdown-menu-content.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-checkbox-item.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-content.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-item.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-radio-group.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-radio-item.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-sub-content.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-sub-trigger.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-trigger.svelte
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer.svelte
pnpm-lock.yaml
sites/docs/package.json

We can reupgrade once this is released: https://github.com/sveltejs/svelte/pull/12016

next: downgrade svelte

---

.changeset/fresh-suits-kiss.md
packages/bits-ui/src/lib/bits/slider/components/slider.svelte

fix: use the `dir` props for rtl support

---

sites/docs/content/components/toggle-group.md
sites/docs/content/components/toggle.md

---
``` ts
<script lang="ts">
import { Toggle } from "bits-ui";
</script>
<Toggle.Root>
<Toggle.Thumb />
<Toggle.Input />
</Toggle.Root>
```
---
``` ts
<script lang="ts">
import { Toggle } from "bits-ui";
</script>
<Toggle.Root/>
```

docs: Update descriptions and structure for Toggle/Group

---

.changeset/eight-guests-lay.md
packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-content.svelte
packages/bits-ui/src/lib/bits/dialog/components/dialog-content.svelte
sites/docs/content/components/toggle.md

Chrome complains of non-passive event listener violations if certain listeners are not *explicitly* marked as non-passive.
Svelte has created [a convenient way](https://github.com/sveltejs/svelte/issues/2068) to add a `nonpassive` event modifer like so:
``` ts
on:touchmove|nonpassive
on:touchstart|nonpassive
```
This PR applies the modifier to events in `Alert Dialog Content` and `Dialog Content`

fix: `nonpassive` modifier to `touchmove` and `touchstart` events

---

package.json
packages/bits-ui/package.json
pnpm-lock.yaml

When trying to use `pnpm` to develop, I see the version required as 8.15.8. However, @huntabyte is already using version 9 himself. So, this is just the repo being outdated with what’s currently supported.

chore: upgrade pnpm version

---

.github/ISSUE_TEMPLATE/3-bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
README.md
package.json
packages/bits-ui/CHANGELOG.md
packages/bits-ui/package.json
pnpm-lock.yaml
sites/docs/content/components/scroll-area.md
sites/docs/package.json
sites/docs/src/app.html
sites/docs/src/lib/content/api-reference/calendar.ts
sites/docs/src/lib/content/api-reference/date-field.ts
sites/docs/src/lib/content/api-reference/extended-types/date-value.ts
sites/docs/src/lib/content/api-reference/extended-types/index.ts

Wow, it's been 4 months since we've merged `main` into `next`

next: resolve merge conflicts with `main`

---

.changeset/plenty-pears-add.md
packages/bits-ui/src/lib/bits/pagination/components/pagination.svelte

Typically onPageChange calls a function and the state of the function is incorrect for the new page because the bound variable `page` is still old.

fix: call `onPageChange` after setting the `page`

---

packages/bits-ui/src/lib/bits/pin-input/components/pin-input.svelte
packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts
packages/bits-ui/src/lib/bits/pin-input/types.ts
packages/bits-ui/src/tests/pin-input/pin-input.test.ts
sites/docs/content/components/pin-input.md
sites/docs/src/lib/components/demo-code-tabs.svelte
sites/docs/src/lib/components/demos/pin-input-demo.svelte
sites/docs/src/lib/components/search.svelte
sites/docs/src/lib/content/api-reference/extended-types/pin-input/index.ts
sites/docs/src/lib/content/api-reference/extended-types/pin-input/pin-input-root-on-paste.md
sites/docs/src/lib/content/api-reference/pin-input.api.ts

Adds the `onPaste` prop on `PinInput.Root`, which can be used to sanitize/clean the pasted text as the developer sees fit. For example, remove hyphens, special characters, etc.
```ts
type OnPaste = (pastedText: string) => string
```
This is more flexible and IMO a better API than trying to remove all special characters (what if someone wants a special character in their pin?), giving full control to the developer/user of the lib.
Addresses #684

next: Expose `onPaste` prop for `PinInput`

---

sites/docs/content/ref.md

fixes the link to the `WithElementRef` page

next(docs): link to WithElementRef

---

.changeset/rare-islands-divide.md
packages/bits-ui/src/lib/bits/tabs/tabs.svelte.ts
packages/bits-ui/src/lib/bits/utilities/portal/portal.svelte
packages/bits-ui/src/lib/internal/afterSleep.ts
packages/bits-ui/src/lib/internal/afterTick.ts
packages/bits-ui/src/lib/internal/arrays.ts
packages/bits-ui/src/lib/internal/callbacks.ts
packages/bits-ui/src/lib/internal/focus.ts
packages/bits-ui/src/lib/internal/getDirectionalKeys.ts
packages/bits-ui/src/lib/internal/types.ts
packages/bits-ui/src/tests/tabs/tabs.test.ts

Aligns the `Tabs` component to the [Tabs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)

fix(next): `Tabs` ARIA attributes

---

.changeset/famous-suits-wash.md
packages/bits-ui/src/lib/bits/alert-dialog/components/alert-dialog-action.svelte
packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
sites/docs/content/components/alert-dialog.md
sites/docs/content/components/dialog.md
sites/docs/src/lib/content/api-reference/alert-dialog.api.ts

`AlertDialog.Action` no longer closes the form, as this causes unexpected behaviors with forms and any other asynchronous actions that need to be taken.

next: `AlertDialog` action changes & Dialog + form docs

---

sites/docs/content/components/select.md

A simple fix for a small mistake in the select documentation. As you can see the `label` is destructured from the item on line 92

docs: use correct reference to label

---

.changeset/shaggy-waves-prove.md
packages/bits-ui/src/lib/bits/slider/components/slider.svelte
packages/bits-ui/src/lib/bits/slider/slider.svelte.ts
packages/bits-ui/src/lib/bits/slider/types.ts
sites/docs/content/components/slider.md
sites/docs/src/lib/content/api-reference/slider.api.ts

A shorter, cleaner, better name for the prop.

next: rename `onValueChangeEnd` to `onValueCommit`

---

.changeset/green-pumpkins-provide.md
packages/bits-ui/src/lib/internal/date-time/calendar-helpers.svelte.ts

fix: calendars not rendering first day of next month

---

.changeset/polite-moons-glow.md
packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts
packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
packages/bits-ui/src/lib/bits/switch/switch.svelte.ts
packages/bits-ui/src/lib/bits/toggle-group/toggle-group.svelte.ts
packages/bits-ui/src/lib/bits/toggle/toggle.svelte.ts

Closes #787
Closes #789 
Closes #788

fix: various pointer/click issues

---

.changeset/two-pugs-tease.md
packages/bits-ui/src/lib/shared/index.ts

Exports `REGEXP_ONLY_DIGITS`, `REGEXP_ONLY_CHARS`, and  `REGEXP_ONLY_DIGITS_AND_CHARS` for use with the `PinInput` component.

next: export regexp helpers for pin input

---

.changeset/calm-snails-refuse.md
packages/bits-ui/src/lib/bits/toggle/toggle.svelte.ts

It's me again. While working on nesting Toggle components within Tooltips (as part of the Origin UI to Svelte port), I discovered that the Toggle.Root component wasn't exposing its internal ID to the DOM. This made it particularly difficult to use the `child` snippet as using the `Toggle.Root`Component as a `Tooltip.Trigger` is not possible. 
[See Stackblitz Repro](https://stackblitz.com/edit/stackblitz-starters-xdgpeu?file=src%2Froutes%2F%2Bpage.svelte)
so i added the ID attribute to the Toggle Root element props for proper DOM referencing. All tests are still passing, so that is something.
- Toggle.Root uses ID internally for ref binding
- The ID is not exposed in the rendered element's attributes
Added ID propagation to the rendered element's attributes in the ToggleRootState class: …

feat: add ID Attribute to Toggle Root Component

---

.changeset/big-fishes-double.md
packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts
packages/bits-ui/src/lib/bits/pin-input/usePasswordManager.svelte.ts
packages/tests/src/tests/pin-input/pin-input.test.ts
sites/docs/content/components/pin-input.md
sites/docs/src/lib/components/demos/pin-input-demo.svelte

next: fix Pin Input `pattern` handling

---

.changeset/rare-waves-lick.md
packages/bits-ui/src/lib/bits/menu/components/menu-checkbox-item.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-item.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-radio-item.svelte
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/menu/types.ts
sites/docs/src/lib/content/api-reference/menu.api.ts

Adds a `closeOnSelect` prop that defaults to `true`. Set it to `false` to prevent the menu from closing when the item is selected (via keyboard or mouse)

next: add `closeOnSelect` prop to menu items

---

.changeset/metal-books-sniff.md
packages/bits-ui/src/lib/bits/pin-input/components/pin-input.svelte
packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts
sites/docs/src/lib/components/demos/pin-input-demo.svelte

For some reason, we were defaulting the `pattern` prop in the `pin-input.svelte` component to `REGEXP_ONLY_DIGITS`, meaning if you didn't provide a pattern (aka you don't want to enforce one), it would fallback to digits.
That default has been removed.
Closes #867

fix: `PinInput` paste not working without pattern

---

.changeset/ten-tigers-exist.md
packages/bits-ui/src/lib/bits/select/select.svelte.ts
packages/tests/src/tests/helpers/select.ts
packages/tests/src/tests/select/select-force-mount-test.svelte
packages/tests/src/tests/select/select-multi-test.svelte
packages/tests/src/tests/select/select-test.svelte
packages/tests/src/tests/select/select.test.ts
sites/docs/src/lib/components/demos/select-demo-multiple.svelte
sites/docs/src/lib/components/demos/select-demo.svelte

Closes #977 
Fixed empty value keyboard selection for `Select`Component. 
The diff is very large, but just because i've added an empty value option in the items array in`packages/tests/src/tests/select/select.test.ts` file. 
Added a few tests as well + enhanced the Components for the Docs to showcase `disabled` options and an option with an empty (`""`) value.  Tho that can be further enhanced, to showcase the possibilities even further.   
I have added  test helpers in `packages/tests/src/tests/helpers/select.ts` because i needed a way to generate a valid testId for the select components. Because there are 3 Components + the test file, it felt right to abstract them away in a helper. I dont't know if that this is your desired approach. Let me know if there is something wrong.

fix: select component to handle empty string values for keyboard

---

.changeset/gold-paws-juggle.md
packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts
packages/tests/src/tests/menubar/menubar.test.ts

fix: `Menubar` navigation between menus while a menu is open

---

.changeset/clever-terms-argue.md
packages/bits-ui/src/lib/bits/command/command.svelte.ts
packages/bits-ui/src/lib/bits/command/components/command.svelte
packages/bits-ui/src/lib/bits/command/types.ts
sites/docs/src/lib/content/api-reference/command.api.ts
sites/docs/src/lib/content/api-reference/extended-types/command/command-on-state-change-prop.md
sites/docs/src/lib/content/api-reference/extended-types/command/index.ts

As i was trying to reimplement [Multiple Selector](https://shadcnui-expansions.typeart.cc/docs/multiple-selector) for [Origin UI Svelte](https://github.com/max-got/originui-svelte/pull/25) i didn't found a way to access the current filtered items for select-{46|47}. [See Original](https://originui.com/selects) "Multiselect, Multiselect with placeholder and clear."
Initially i wanted to give the user something like [`useCommandState`](https://github.com/pacocoursey/cmdk#usecommandstatestate--stateselectedfield), but that felt wrong. But maybe there is a better solution. I just wanted to kickstart something like this! Feel free to close this, if you think that is the wrong approach!
This PR introduces a new `onStateChange` callback to the Command component, allowing consumers to track and …

feat: add `onStateChange` callback to Command component

---

.changeset/clever-singers-wait.md
packages/bits-ui/src/lib/bits/command/command.svelte.ts

fix: command arrow navigation after empty state

---

.changeset/grumpy-clouds-remember.md
packages/bits-ui/src/lib/app.d.ts
packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts
packages/bits-ui/src/lib/bits/checkbox/components/checkbox-group-label.svelte
packages/bits-ui/src/lib/bits/checkbox/components/checkbox-group.svelte
packages/bits-ui/src/lib/bits/checkbox/components/checkbox.svelte
packages/bits-ui/src/lib/bits/checkbox/exports.ts
packages/bits-ui/src/lib/bits/checkbox/types.ts
packages/bits-ui/src/lib/internal/use-id.ts
packages/tests/src/tests/checkbox/checkbox-group-test.svelte
packages/tests/src/tests/checkbox/checkbox.test.ts
sites/docs/content/components/checkbox.md
sites/docs/src/lib/components/demos/checkbox-demo-group.svelte
sites/docs/src/lib/components/demos/index.ts
sites/docs/src/lib/content/api-reference/checkbox.api.ts
sites/docs/src/lib/content/api-reference/extended-types/checkbox/checkbox-group-on-value-change-prop.md
sites/docs/src/lib/content/api-reference/extended-types/checkbox/index.ts

Closes #999 
This pull request introduces a new feature for the `Checkbox` component, adding support for `Checkbox.Group` and `Checkbox.GroupLabel` components. 
* Implemented `Checkbox.Group` and `Checkbox.GroupLabel` components to allow grouping of checkboxes and providing a label for the group. 
* Added new test cases for `Checkbox.Group` and `Checkbox.GroupLabel` to verify their functionality and ensure they integrate correctly with the existing `Checkbox` component.

next: `Checkbox.Group`

---

.changeset/real-houses-talk.md
packages/bits-ui/package.json

Resolves `warn: incorrect peer dependency "svelte@5.1.9"` for Svelte 5 projects using `bits-ui`.

chore: update svelte peer dependency

---

.changeset/yellow-lies-vanish.md
packages/bits-ui/src/lib/bits/accordion/accordion.svelte.ts
packages/bits-ui/src/lib/bits/collapsible/collapsible.svelte.ts
packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
packages/bits-ui/src/lib/bits/pagination/pagination.svelte.ts
packages/bits-ui/src/lib/bits/popover/components/popover-content-static.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts
packages/tests/package.json
packages/tests/src/tests/accordion/accordion-multi-test-controlled.svelte
packages/tests/src/tests/accordion/accordion-single-test-controlled.svelte
packages/tests/src/tests/accordion/accordion.test.ts
packages/tests/src/tests/alert-dialog/alert-dialog.test.ts
packages/tests/src/tests/dialog/dialog.test.ts
packages/tests/src/tests/popover/popover.test.ts
pnpm-lock.yaml

This PR reverts some changes to event handling made in a previous PR where we switched most of the `onclick` events to `onpointerdown`.
After some consideration and feedback, `onclick` makes the most sense in most places, however, we are keeping `onpointerdown` for the various menus/select/tabs where they make sense and feel better.

next: `onpointerdown` -> `onclick`

---

.changeset/rare-gorillas-invite.md
packages/bits-ui/src/lib/bits/tooltip/types.ts
packages/bits-ui/src/lib/bits/utilities/floating-layer/types.ts
sites/docs/src/routes/(main)/sink/+page.svelte

fix: expose `updatePositionStrategy` prop for tooltip content

---

.changeset/spotty-bottles-battle.md
packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts

fix: dialog close/cancel `pointerdown` -> `click`

---

.changeset/dry-spiders-learn.md
packages/bits-ui/src/lib/bits/accordion/accordion.svelte.ts
packages/bits-ui/src/lib/bits/slider/components/slider.svelte
packages/bits-ui/src/lib/bits/slider/slider.svelte.ts
packages/bits-ui/src/lib/bits/slider/types.ts
packages/tests/src/tests/slider/slider-range-test.svelte
packages/tests/src/tests/slider/slider-test-multi.svelte
packages/tests/src/tests/slider/slider.test.ts
sites/docs/content/components/slider.md
sites/docs/src/lib/components/api-ref/prop-type-content.svelte
sites/docs/src/lib/components/api-section.svelte
sites/docs/src/lib/components/demos/index.ts
sites/docs/src/lib/components/demos/slider-demo-multiple.svelte
sites/docs/src/lib/components/demos/slider-demo.svelte
sites/docs/src/lib/content/api-reference/extended-types/slider/slider-root-on-value-change.md
sites/docs/src/lib/content/api-reference/helpers.ts
sites/docs/src/lib/content/api-reference/slider.api.ts
sites/docs/src/routes/(main)/sink/+page.svelte

Closes #1031 
Now we no longer need to use an array with a single value as the slider's value if we only need one value, while still giving the flexibility to render multiple thumbs should you need them.
```svelte
<script lang="ts">
import { Slider } from "bits-ui"
let singleValue = $state(50)
let multiValue = $state([25, 75])
</script>
<Slider.Root type="single" bind:value={singleValue} />
<Slider.Root type="multiple" bind:value={multiValue} />
```
This API change aligns with the other components that provide multiple value types, such as the `Accordion`, `Combobox`, `Select`, `Calendar`, etc.

breaking: Slider `type` prop for `number` or `number[]` value

---

.changeset/khaki-drinks-reflect.md
packages/bits-ui/src/lib/bits/button/components/button.svelte
packages/bits-ui/src/lib/bits/button/types.ts
sites/docs/src/lib/content/api-reference/button.api.ts

Alternative to #1039 
Implements the method used in the [blog post](https://www.scottohara.me/blog/2021/05/28/disabled-links.html):
```svelte
<a role="link" aria-disabled="true">Learn something!</a>
```

feat: Allow `<Button/>` with `href` to be disabled

---

sites/docs/content/components/command.md

There is a small typo on `command.md` where it should import Command instead of Combobox.

fix: Correct to Command

---

.changeset/afraid-glasses-grow.md
packages/bits-ui/src/lib/bits/index.ts
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/utilities/is-using-keyboard/is-using-keyboard.svelte.ts
packages/bits-ui/src/lib/index.ts
packages/tests/src/tests/utilities/is-using-keyboard/index.test.ts
packages/tests/src/tests/utilities/is-using-keyboard/is-using-keyboard-test.svelte
sites/docs/content/utilities/is-using-keyboard.md

Fixes #1070
---
I took the opportunity to optimize the determination of the user's input mode (pointer or keyboard). Now, only three event listeners are registered and can be shared between multiple components.
I took inspiration from @huntabyte's branch `fix/focus-scoping` where a class `IsUsingKeyboard` is already implemented.
---
Many thanks to @chbert with whom I troubleshot this issue extensively :)

fix: dangling event listeners on menu

---

.changeset/gentle-chefs-wait.md
packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts
packages/tests/src/tests/range-calendar/range-calendar-test.svelte
packages/tests/src/tests/range-calendar/range-calendar.test.ts
sites/docs/content/components/checkbox.md
sites/docs/src/routes/(main)/sink/+page.svelte
sites/docs/src/routes/(main)/sink/range-cal.svelte

fix: allow `RangeCalendar` value to be cleared

---

sites/docs/content/ref.md

The code samples in the documentation on Ref did not work with Svelte 5 (Cannot do `bind:ref={undefined}` when `ref` has a fallback value), so I changed them.\
I hope this is the right way to do it.

Documentation update: Change triggerRef to be initialized as null in Ref

---

.changeset/orange-socks-share.md
packages/bits-ui/package.json
pnpm-lock.yaml

Closes #1062 
This pull request updates the `runed` package to support Astro builds. It was previously failing because during build, `esm-env` returns `true` for the `BROWSER` check, so we also added a defined check to runed.

fix: Astro builds failing

---

.changeset/chatty-plums-judge.md
packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts
packages/tests/src/tests/pin-input/pin-input.test.ts
sites/docs/src/lib/components/demos/pin-input-demo.svelte

The issue was that we were preventing default on non-matching keys, such as `v` regardless of whether `ctrlKey` or `metaKey` was true.

fix: Pin Input paste behavior

---

.changeset/tough-carrots-grin.md
packages/bits-ui/src/lib/bits/utilities/dismissible-layer/use-dismissable-layer.svelte.ts
packages/bits-ui/src/lib/internal/dom.ts
packages/tests/src/tests/combobox/combobox.test.ts
packages/tests/src/tests/dialog/dialog.test.ts
packages/tests/src/tests/popover/popover.test.ts
packages/tests/src/tests/select/select.test.ts

fix: account for `clientX` and `clientY` in "outsidePress"

---

.changeset/late-ants-float.md
packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts

fix: allow `maxValue` to be selected as complete range 

---

.changeset/few-coats-greet.md
packages/bits-ui/src/lib/bits/pin-input/pin-input.svelte.ts

fix: Pin Input paste without transformer violating match regex

---

packages/bits-ui/src/lib/bits/navigation-menu/navigation-menu.svelte.ts
sites/docs/content/components/navigation-menu.md
sites/docs/src/lib/components/demos/index.ts
sites/docs/src/lib/components/demos/navigation-menu-demo-force-mount.svelte

docs: navigation menu forceMount prop

---

.changeset/big-dogs-sing.md

Well, since somehow way back when (7 years ago) bits-ui 1.0.0-1.0.7 was published (no longer on registry), so we must start at 1.1.0.

chore: release

---

.changeset/hot-shirts-grin.md
.changeset/mean-walls-wonder.md
docs/src/lib/content/api-reference/combobox.api.ts
docs/src/lib/content/api-reference/select.api.ts
package.json
packages/bits-ui/src/lib/bits/context-menu/components/context-menu-content-static.svelte
packages/bits-ui/src/lib/bits/context-menu/components/context-menu-content.svelte
packages/bits-ui/src/lib/bits/dropdown-menu/components/dropdown-menu-content-static.svelte
packages/bits-ui/src/lib/bits/dropdown-menu/components/dropdown-menu-content.svelte
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-content-static.svelte
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-content.svelte
packages/bits-ui/src/lib/bits/link-preview/link-preview.svelte.ts
packages/bits-ui/src/lib/bits/menu/components/menu-content-static.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-content.svelte
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/menubar/components/menubar-content-static.svelte
packages/bits-ui/src/lib/bits/menubar/components/menubar-content.svelte
packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts
packages/bits-ui/src/lib/bits/popover/components/popover-content-static.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts
packages/bits-ui/src/lib/bits/select/components/select-content-static.svelte
packages/bits-ui/src/lib/bits/select/components/select-content.svelte
packages/bits-ui/src/lib/bits/select/select.svelte.ts
packages/bits-ui/src/lib/bits/select/types.ts
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-content-static.svelte
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-content.svelte
packages/bits-ui/src/lib/bits/tooltip/tooltip.svelte.ts

Closes #1189 
--
Additionally, this PR removes an improperly exposed prop - `onCloseAutoFocus` on the `Select.Content/ContentStatic` and `Combobox.Content/ContentStatic`.
If you were using this prop previously, it was not doing anything as we were not forwarding it through the components.
We manage focus differently for the `Select` and `Combobox`, using the `aria-activedescendent` property, so there is no use in an `onCloseAutoFocus` or `onOpenAutoFocus` prop, I just forgot to omit it from the exposed type.

fix: `disableCloseOnTriggerClick` prop for `Tooltip` component

---

.changeset/eleven-lamps-relate.md
docs/src/lib/components/demos/date-range-picker-demo.svelte
packages/bits-ui/src/lib/bits/date-range-field/date-range-field.svelte.ts
tests/src/tests/date-range-picker/date-range-picker-test.svelte
tests/src/tests/date-range-picker/date-range-picker.test.ts
tests/src/tests/label/label.test.ts
tests/src/tests/link-preview/link-preview.test.ts
tests/src/tests/menubar/menubar.test.ts
tests/src/tests/pagination/pagination.test.ts
tests/src/tests/pin-input/pin-input.test.ts
tests/src/tests/popover/popover.test.ts
tests/src/tests/progress/progress.test.ts
tests/src/tests/radio-group/radio-group.test.ts
tests/src/tests/range-calendar/range-calendar.test.ts

Closes #1194 
Fixes an issue where the DateRangePicker wouldn't update the value under certain conditions due to conflicting effects.

fix: `DateRangePicker` not updating value under certain conditions

---

.changeset/fresh-snails-report.md
docs/content/components/meter.md
docs/content/components/progress.md
docs/src/lib/components/demos/index.ts
docs/src/lib/components/demos/meter-demo-custom.svelte
docs/src/lib/components/demos/meter-demo.svelte
docs/src/lib/components/demos/progress-demo-custom.svelte
docs/src/lib/components/demos/progress-demo.svelte
docs/src/lib/components/index.ts
docs/src/lib/content/api-reference/index.ts
docs/src/lib/content/api-reference/meter.api.ts
packages/bits-ui/src/lib/bits/index.ts
packages/bits-ui/src/lib/bits/meter/components/meter.svelte
packages/bits-ui/src/lib/bits/meter/exports.ts
packages/bits-ui/src/lib/bits/meter/index.ts
packages/bits-ui/src/lib/bits/meter/meter.svelte.ts
packages/bits-ui/src/lib/bits/meter/types.ts
packages/bits-ui/src/lib/index.ts
packages/bits-ui/src/lib/types.ts
tests/src/tests/meter/meter-test.svelte
tests/src/tests/meter/meter.test.ts
tests/src/tests/progress/progress.test.ts

As discussed in #1183, we currently lack a dedicated `Meter` component. 
This absence can lead to developers incorrectly using the `Progress` component to represent values on a gauge or scale, which is semantically inaccurate and can lead to accessibility issues.  The `Progress` component is intended for indicating the completion status of a process, while `Meter` represents a measured value within a known range.
This PR introduces the missing `Meter` component to the library.
Usage of `Meter` is similar to `Progress`:
```svelte
<script lang="ts">
import { Meter } from "bits-ui"
let value = $state(3000);
const max = 4000
</script>
<Meter.Root {value} {max} aria-label="Remaining tokens" aria-valuetext="{value} out of {max}" />
```

feat: `Meter` component

---

.changeset/warm-taxis-type.md
packages/bits-ui/src/lib/bits/radio-group/radio-group.svelte.ts
tests/src/tests/radio-group/radio-group-popover-test.svelte
tests/src/tests/radio-group/radio-group.test.ts

Closes #1198 
We now check if a value is set on the root and compare that to determine the `RadioGroup.Item`'s `tabindex` before it is computed within an `$effect`. The delay in computation caused focus to accidentally be set to the first radio item, due to the default `tabindex` being `0`.

fix: `RadioGroup` tabindex calculations

---

.changeset/cyan-days-hang.md
.changeset/tiny-brooms-notice.md
docs/src/lib/components/demos/combobox-demo.svelte
docs/src/lib/components/demos/select-demo-custom.svelte
docs/src/lib/components/demos/select-demo-multiple.svelte
docs/src/lib/components/demos/select-demo-transition.svelte
docs/src/lib/components/demos/select-demo.svelte
packages/bits-ui/src/lib/bits/select/components/select-content.svelte
packages/bits-ui/src/lib/bits/select/select.svelte.ts

This PR fixes an issue where when a transition/animation existed on the `Combobox/Select` `.Content`, the selected item wouldn't be fully scrolled into view when a `<*.ScrollDownButton>` is rendered.
It also fixes an issue where `focus-visible` would be applied to the `Select.Trigger` on close even if no keyboard interactions took place between opening and closing.
Closes #1202

fix: select/combobox scroll issues

---

.changeset/four-plums-invite.md
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts

fix: `Popover.Trigger` incorrectly receiving focus-visible  

---

docs/content/components/date-picker.md

Fixes a [snippet conflict](https://svelte.dev/docs/svelte/compiler-errors#snippet_conflict) error that appears when pasting in the structure

docs: fix a snippet conflict in `DatePicker`'s structure

---

.changeset/mighty-windows-appear.md
docs/content/components/tooltip.md
docs/src/lib/components/demos/index.ts
docs/src/lib/components/demos/tooltip-demo-custom-anchor.svelte
packages/bits-ui/src/lib/bits/tooltip/types.ts
tests/src/tests/tooltip/tooltip-test.svelte
tests/src/tests/tooltip/tooltip.test.ts
tests/src/tests/utils.ts

fix: expose `customAnchor` type for `Tooltip.Content` props

---

docs/content/components/select.md

Found a documentation error in the [Reusable Components](https://bits-ui.com/docs/components/select#reusable-components) example of the Select component:
`{item.label}` should be `{label}`. `item` does not exist since `Select.Item` is destructured as `{value} {label} {disabled}`.

docs: Select example to use the destructured label

---

README.md

Added a modified screen capture from Bits UI homepage to freshen up the readme. I think the example components are really nice looking and deserves a place there. Feel free to close the PR if not suitable 👍

docs: add hero to readme

---

.changeset/cold-horses-destroy.md
packages/bits-ui/src/lib/bits/context-menu/components/context-menu-content.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-sub-content-static.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-sub-content.svelte

Some components accept `trapFocus` prop, but don't correctly forward it to the underlying components.
There are also some components that *don't* accept a `trapFocus` prop, but I left those intact because I'm not sure if that's intentional.

fix: forward `trapFocus` prop

---

sites/docs/content/components/menubar.md

This pull request fixes a typo in the `menubar.md` file. It corrects the mismatch in the code snippet by using the `onValueChange` prop as described in the paragraph. Resolves issue #1314.

docs: correct typo in menubar.md code snippet (#1314)

---

docs/content/styling.md

This pull request fixes a typo in the `styling.md` file. It updates the incorrect class name `button` to `accordion-trigger`, which is the correct global class defined in the `app.css` code snippet under `Global Classes`.

docs: correct typo in styling.md code snippet

---

.changeset/nice-wolves-jog.md
docs/src/lib/components/demos/select-demo.svelte
packages/bits-ui/src/lib/bits/select/select.svelte.ts
packages/bits-ui/src/lib/internal/arrays.test.ts
packages/bits-ui/src/lib/internal/arrays.ts
packages/bits-ui/src/lib/internal/use-data-typeahead.svelte.ts
packages/bits-ui/src/lib/internal/use-dom-typeahead.svelte.ts

This PR enhances the typeahead logic in the `Select` component, particularly to intelligently support spaces in typeahead searches.
For example, in the following video, you'll notice that since `Dark Green` is the only possible match of "dark+space", pressing space after dark will select it, but since there are multiple "Sunset+space" options, it will respect the space as long as it's typed within 1 second of the previous character, and not select/close.
https://github.com/user-attachments/assets/ab6568d0-d2fd-46cc-a3b5-ac7d14ef943d
Closes #1304

fix(Select): enable space support in typeahead logic

---

.changeset/slimy-kings-turn.md
packages/bits-ui/src/lib/bits/command/command.svelte.ts

When you use `Command` with a large number of items it lags every time you open it because all elements are sorted once for each item that is added instead of once after all items are added.

fix(Command): command sort only once per tick

---

docs/src/lib/content/api-reference/context-menu.api.ts
docs/src/lib/content/api-reference/dropdown-menu.api.ts

This PR corrects a typo in the description property of the `group` const in the following files:
docs/src/lib/content/api-reference/dropdown-menu.api.ts
docs/src/lib/content/api-reference/context-menu.api.ts
The updated description now correctly references its child `GroupHeading` component.

docs: correct typo in APISchema descriptions for `group` in dropdown-menu.api.ts and context-menu.api.ts

---

.changeset/silver-poets-run.md
packages/bits-ui/src/lib/bits/calendar/calendar.svelte.ts
packages/bits-ui/src/lib/bits/date-field/date-field.svelte.ts
packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts
packages/bits-ui/src/lib/internal/date-time/calendar-helpers.svelte.ts
packages/bits-ui/src/lib/internal/date-time/utils.ts

This PR fixes a regression introduced in v1.3.6 (PR #1264) affecting date serialization. 
The current implementation uses @internationalized/date `toString()` for serializing `date-value` attribute. When the boxed `DateValue` is a `ZonedDateTime`, calling `toString()` includes timezone information, causing compatibility issues with the `parseDate` function call in `calendar-helpers.svelte.js` which seems to only be able to handle ISO 8601 UTC strings.
This PR modifies the date serialization to consistently use `toAbsoluteString()` instead, generating ISO 8601 UTC dates regardless of the underlying `DateValue` type.

Fix date formatting in date-value attribute

---

.changeset/red-wolves-hug.md
packages/bits-ui/src/lib/bits/calendar/components/calendar.svelte

fix(Calendar): ensure default value is not a string

---

.changeset/many-cooks-rush.md
packages/bits-ui/src/lib/bits/command/command.svelte.ts

fix(Command): ensure filtered is always defined, even if not filtering

---

docs/content/components/combobox.md

I believe it should be outside of `Combobox.Viewport`

docs: Fix Combobox ScrollDownButton position

---

.changeset/thick-ducks-train.md
packages/bits-ui/src/lib/bits/utilities/focus-scope/use-focus-scope.svelte.ts

> if someone wants to look into this and add undefined checks (in places they really shouldn't need to be), then I will consider merging a PR to support compat mode
from discussion #1302
I tried to find out why the box is empty in compat mode, but no luck!
This pull request includes a small change to the `useFocusScope` function in the `packages/bits-ui/src/lib/bits/utilities/focus-scope/use-focus-scope.svelte.ts` file. The change ensures that the `onCloseAutoFocus.current` method is only called if it is not null or undefined.
* [`packages/bits-ui/src/lib/bits/utilities/focus-scope/use-focus-scope.svelte.ts`](diffhunk://#diff-1120b01d2c11483511424f952b216169ec73ea4b3e1d63f2fd791adda80c131fL199-R199): Added optional chaining to the `onCloseAutoFocus.current` method call to prevent …

fix(FocusScope): safely call onCloseAutoFocus handler if defined

---

.changeset/fresh-gifts-bathe.md
.changeset/tasty-bobcats-begin.md
docs/content/components/slider.md
docs/src/lib/components/demos/index.ts
docs/src/lib/components/demos/slider-demo-ticks.svelte
packages/bits-ui/src/lib/bits/slider/slider.svelte.ts

Ticks broke after pull request #1338.
There is an issue with the slider where the ticks were assigned an incorrect left percentage style when the minimum and maximum values were different from 0 and 100.

fix(Slider): update tick position calculation for consistent scaling

---

docs/content/components/command.md

This pull request replaces the combobox input with the command input in the command component's structure example.
Ref #1388

docs: use command input in structure example

---

.changeset/olive-apes-stare.md
.changeset/violet-plums-smash.md
packages/bits-ui/src/lib/bits/date-range-field/date-range-field.svelte.ts
tests/src/tests/date-range-field/date-range-field.test.ts
tests/src/tests/date-range-picker/date-range-picker.test.ts

Keyboard input is currently broken on the `DateRangePicker`. This small change removes the logic to update the start date automatically so keyboard input works fine.
https://github.com/huntabyte/bits-ui/issues/1348

fix(DateRangePicker): do not update start date automatically

---

packages/bits-ui/src/lib/bits/dialog/dialog.svelte.ts
tests/src/tests/dialog/dialog.test.ts

Fixes https://github.com/huntabyte/bits-ui/issues/1417
It feels like you didn't mean to leave this commented-out 😅 
Maybe a `getByRole('heading')` test would be a good idea, but you don't use any `getByRole` selectors elsewhere, so I didn't want to start a trend you may not like 😄

fix(Dialog): ensure `Dialog.Title` has the "heading" role

---

.changeset/popular-ducks-smile.md

Forgot to add changeset for #1417

fix(Dialog): ensure `role="heading"` exists on title

---

.changeset/nasty-brooms-tease.md
docs/src/lib/content/api-reference/helpers.ts
docs/src/lib/content/api-reference/navigation-menu.api.ts
packages/bits-ui/src/lib/bits/navigation-menu/components/navigation-menu-content.svelte
tests/src/tests/navigation-menu/navigation-menu-test.svelte
tests/src/tests/navigation-menu/navigation-menu.test.ts

Closes #1458, I also added documentation on the `Sub` element that was missing

fix(NavigationMenu): render `Content` without `Viewport`

---

.changeset/red-moles-greet.md
docs/src/lib/components/demos/slider-demo-multiple.svelte
docs/src/lib/components/demos/slider-demo-ticks.svelte
docs/src/lib/components/demos/slider-demo.svelte
docs/src/lib/content/api-reference/slider.api.ts
packages/bits-ui/src/lib/bits/slider/components/slider-thumb.svelte
packages/bits-ui/src/lib/bits/slider/slider.svelte.ts
packages/bits-ui/src/lib/bits/slider/types.ts

Also adjusts example styles to use the data attribute instead of the active pseudo class.
Maybe we should expose this as a bindable prop as well? Not sure.

feat(Slider): Expose active state on thumb

---

.changeset/early-wasps-tell.md
.changeset/lazy-geese-kneel.md
.changeset/nervous-jeans-cover.md
docs/content/components/context-menu.md
docs/content/components/dropdown-menu.md
docs/content/components/menubar.md
docs/src/lib/content/api-reference/context-menu.api.ts
docs/src/lib/content/api-reference/dropdown-menu.api.ts
docs/src/lib/content/api-reference/menu.api.ts
docs/src/lib/content/api-reference/menubar.api.ts
packages/bits-ui/src/lib/bits/context-menu/exports.ts
packages/bits-ui/src/lib/bits/context-menu/types.ts
packages/bits-ui/src/lib/bits/dropdown-menu/exports.ts
packages/bits-ui/src/lib/bits/dropdown-menu/types.ts
packages/bits-ui/src/lib/bits/menu/components/menu-checkbox-group.svelte
packages/bits-ui/src/lib/bits/menu/components/menu-checkbox-item.svelte
packages/bits-ui/src/lib/bits/menu/exports.ts
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/menu/types.ts
packages/bits-ui/src/lib/bits/menubar/exports.ts
packages/bits-ui/src/lib/bits/menubar/types.ts
tests/src/tests/context-menu/context-menu-test.svelte
tests/src/tests/context-menu/context-menu.test.ts
tests/src/tests/dropdown-menu/dropdown-menu-test.svelte
tests/src/tests/dropdown-menu/dropdown-menu.test.ts

Closes #1266 
This pull request introduces a new `CheckboxGroup` component to various menus (`ContextMenu`, `DropdownMenu`, and `Menubar`), along with corresponding documentation and API updates. The changes include the addition of the component, updates to documentation to demonstrate its usage, and modifications to type definitions and exports to support the new functionality.
* **`CheckboxGroup` Component**: Added the `CheckboxGroup` component to group multiple `CheckboxItem` components within menus, allowing multiple selections. This includes updates to the `ContextMenu`, `DropdownMenu`, and `Menubar` implementations. 
* **Usage Examples**: Added examples for `CheckboxGroup` and `RadioGroup` in the documentation for `ContextMenu`, `DropdownMenu`, and `Menubar`. These examples …

feat(Menu): add `*Menu.CheckboxGroup` component

---

.changeset/little-clocks-worry.md
docs/src/lib/content/api-reference/extended-types/shared/index.ts
docs/src/lib/content/api-reference/extended-types/shared/slider-thumb-positioning-prop.md
docs/src/lib/content/api-reference/slider.api.ts
packages/bits-ui/src/lib/bits/slider/components/slider.svelte
packages/bits-ui/src/lib/bits/slider/slider.svelte.ts
packages/bits-ui/src/lib/bits/slider/types.ts
packages/bits-ui/src/lib/shared/index.ts

Looking for feedback before I add docs - not sure if this property should be moved to the thumbs themselves somehow
Motivation:
With an equal padding around the slider, the containment makes alignment look 'off'.

feat(Slider): Add slider thumb positioning prop

---

.changeset/dry-bees-yawn.md
.changeset/moody-carrots-ring.md
docs/content/components/navigation-menu.md
docs/src/lib/components/demos/index.ts
docs/src/lib/components/demos/navigation-menu-no-viewport-demo.svelte
docs/src/lib/components/demos/navigation-menu-submenu-demo.svelte
packages/bits-ui/src/lib/bits/navigation-menu/components/navigation-menu-viewport.svelte
packages/bits-ui/src/lib/bits/navigation-menu/navigation-menu.svelte.ts
tests/src/tests/navigation-menu/navigation-menu.test.ts

This pull request introduces bug fixes and enhancements to the `NavigationMenu` component in the `bits-ui` library, along with updates to the documentation and demos. The changes address issues with transitions, improve submenu behavior, and add new demo components for better visualization.
* Fixed an issue where moving from a submenu trigger to a menu item in the same menu did not close the submenu (`NavigationMenu`).
* Resolved problems with non-viewport transitions in the `NavigationMenu` component.
* Updated `navigation-menu.md` to include new demos for submenus and non-viewport transitions, replacing code snippets with interactive previews.
* Added `navigation-menu-no-viewport-demo.svelte` to demonstrate `NavigationMenu` transitions without a viewport.
* Added …

fix(NavigationMenu): submenu/viewport residual transition issues

---

tests/src/tests/slider/slider-test-with-labels.svelte
tests/src/tests/slider/slider.test.ts

This pull request introduces a new `SliderWithLabelsTest` component and updates the test suite for the slider to include comprehensive tests for sliders with tick and thumb labels. The changes focus on adding label-related functionality and ensuring thorough test coverage for various scenarios.
* **Tick Labels**:
- Tests verify tick labels' accessibility, data attributes, content, positioning, and behavior under different states (e.g., disabled, vertical orientation, and custom steps). 
* **Thumb Labels**:
- Tests ensure thumb labels render correctly with the right attributes, content, and behavior, including active states, disabled states, and position updates during interactions. 
* **Custom Scenarios**:
- Additional tests handle edge cases like fractional step values, multiple thumbs, …

chore: test slider labels

---

.changeset/twelve-carpets-juggle.md
docs/src/lib/content/api-reference/combobox.api.ts
docs/src/routes/(docs)/sink/+page.svelte
docs/src/routes/(docs)/sink/combobox.svelte
packages/bits-ui/src/lib/bits/combobox/components/combobox-input.svelte
packages/bits-ui/src/lib/bits/combobox/components/combobox.svelte
packages/bits-ui/src/lib/bits/combobox/types.ts
packages/bits-ui/src/lib/bits/select/components/select.svelte
packages/bits-ui/src/lib/bits/select/select.svelte.ts
tests/src/tests/combobox/combobox-test.svelte
tests/src/tests/combobox/combobox.test.ts

Closes #1317 
This pull request introduces a new feature to the `Combobox` component, allowing programmatic synchronization of the input value via the `inputValue` prop.
* **`Combobox` Enhancements:**
- Added a new `inputValue` prop to `Combobox.Root` for synchronizing the displayed input value with external updates.

feat(Combobox): expose `inputValue` prop on `Combobox.Root`

---

.changeset/clear-drinks-scream.md
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-content-static.svelte
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-content.svelte
packages/bits-ui/src/lib/bits/tooltip/components/tooltip-trigger.svelte
packages/bits-ui/src/lib/bits/tooltip/components/tooltip.svelte
packages/bits-ui/src/lib/bits/tooltip/tooltip.svelte.ts
packages/bits-ui/src/lib/bits/utilities/floating-layer/components/floating-layer-anchor.svelte
packages/bits-ui/src/lib/bits/utilities/floating-layer/components/floating-layer-content.svelte
packages/bits-ui/src/lib/bits/utilities/floating-layer/components/floating-layer.svelte
packages/bits-ui/src/lib/bits/utilities/floating-layer/types.ts
packages/bits-ui/src/lib/bits/utilities/floating-layer/use-floating-layer.svelte.ts
packages/bits-ui/src/lib/bits/utilities/popper-layer/popper-layer-inner.svelte
packages/bits-ui/src/lib/bits/utilities/popper-layer/types.ts
tests/src/tests/tooltip/tooltip-popover-test.svelte
tests/src/tests/tooltip/tooltip.test.ts

Closes #1523 
This pull request introduces changes to the `bits-ui` library to enhance the behavior of tooltips, specifically enabling them to be composed with other floating components like popovers. The update includes modifications to the tooltip and floating layer components, as well as the addition of new tests to ensure the functionality works as expected.
* **Tooltip Composition with Floating Components**: Updated `Tooltip.Trigger` and related components to support composition with other floating component triggers, such as popovers.
* **New Test for Tooltip and Popover Composition**: Added a test case to validate that tooltips can be composed with popovers, ensuring correct behavior when the same trigger is used for both components.

fix(Tooltip): `Tooltip.Trigger` composition

---

.changeset/old-clocks-stare.md
packages/bits-ui/src/lib/bits/rating-group/rating-group.svelte.ts

This PR fixes an issue where the rating group `data-state` would not reflect the current value when showing the preview. This is obvious when you hover the input while using the arrow keys. 
We can fix this by resetting the `#hoverValue` to null when navigating with the keyboard.
Broken Example:

fix(rating-group): Ensure data-state reflects value correctly when showing preview

---

.changeset/short-candles-clap.md
packages/bits-ui/src/lib/bits/tabs/tabs.svelte.ts

fix: Expose `data-orientation` on `Tabs.Content`

---

.changeset/slimy-beers-train.md
packages/bits-ui/src/lib/bits/utilities/scroll-lock/scroll-lock.svelte

fix: body styles aren't touched when `preventScroll={false}`

---

.changeset/gold-crews-argue.md
docs/content/components/radio-group.md
docs/src/lib/components/demos/index.ts
docs/src/lib/components/demos/radio-group-demo-disabled.svelte
docs/src/lib/components/demos/radio-group-demo-readonly.svelte
docs/src/lib/content/api-reference/radio-group.api.ts
docs/src/lib/content/utils.ts
packages/bits-ui/src/lib/bits/radio-group/components/radio-group.svelte
packages/bits-ui/src/lib/bits/radio-group/radio-group.svelte.ts
packages/bits-ui/src/lib/bits/radio-group/types.ts
tests/src/tests/radio-group/radio-group.test.ts

This pull request introduces a new `readonly` property to the `RadioGroup` component.
* Added a `readonly` prop to the `RadioGroup.Root` component to make it readonly, preventing value changes while still allowing focus and navigation.
* Updated the `RadioGroup` state and behavior to respect the `readonly` property, including preventing value changes on clicks, focus, or keyboard interactions when `readonly` is true.

feat(RadioGroup): add `readonly` prop

---

.changeset/orange-friends-say.md
packages/bits-ui/package.json
packages/bits-ui/src/lib/bits/command/command.svelte.ts
packages/bits-ui/src/lib/internal/css-escape.test.ts
packages/bits-ui/src/lib/internal/css-escape.ts
pnpm-lock.yaml

This pull request addresses a bug related to the use of `css.escape` in `bits-ui` by replacing it with an alternative approach. 
Fixes #1607

fix: replace `css.escape` to prevent `this` issue

---

.changeset/loose-dogs-rule.md
packages/bits-ui/src/lib/bits/command/command.svelte.ts

Kinda a weird hack but it works better than only scrolling to the item itself.

fix(Command): Ensure selected item is visible when command is in grid mode

---

.changeset/every-snails-clean.md
docs/src/lib/components/demos/checkbox-demo-group.svelte
packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts
packages/bits-ui/src/lib/bits/checkbox/components/checkbox-group.svelte

Fixes #1613 
Ensure's `onValueChange` is called only once per change for checkbox groups.

fix(Checkbox): ensure   isn't called more than once per change

---

.changeset/breezy-plums-relax.md
packages/bits-ui/src/lib/bits/calendar/calendar.svelte.ts
packages/bits-ui/src/lib/bits/range-calendar/range-calendar.svelte.ts

This pull request introduces a fix to ensure that days outside the current month are properly disabled when the `disableDaysOutsideMonth` option is enabled. The changes primarily affect the behavior of calendar components.
Fixes #1611

fix(Calendar): ensure `disableDaysOutsideMonth` is respected

---

docs/content/getting-started.md

Getting-started accordion example missing the required `type` prop, non-functional when copied directly. Replaced with working example from the accordion component docs.
Discouraging for new devs when their first copy-paste doesn't work.

Docs: Fix non-functional accordion example in getting started guide

---

.changeset/green-pugs-applaud.md
packages/bits-ui/src/lib/bits/select/select.svelte.ts

This PR fixes an issue where pressing `Enter` after typing a value that doesn't match any `Combobox` item would still select the last highlighted item, even though it was no longer visible. (See #1644)
The issue occurred because highlight candidates were being collected **_before_** the `Combobox` content was updated. This led to stale items being highlighted, even when no matching items were shown.
The highlight logic has been refactored to rely on the actual mounted content of the `Select`, rather than attempting to collect candidates immediately when the input value changes.
This is a more reliable approach because the timing of content updates is entirely up to the developer and it can vary depending on how filtering and rendering are implemented.
Changes:
- The logic to update the …

fix(Combobox): prevent selection of last highlighted item on invalid input (#1644)

---

.changeset/plain-radios-eat.md
docs/src/lib/components/demos/checkbox-demo.svelte
packages/bits-ui/src/lib/bits/checkbox/checkbox.svelte.ts
tests/vite.config.ts

fix(Checkbox): prevent default `onclick` to support labels

---

.changeset/short-lights-beg.md
packages/bits-ui/src/lib/bits/menu/menu.svelte.ts
packages/bits-ui/src/lib/bits/menubar/menubar.svelte.ts
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts
packages/bits-ui/src/lib/bits/utilities/focus-scope/focus-scope.svelte.ts

Fixes #1673.
When dialogs are removed from the DOM, it can sometimes happen that onCloseAutoFocus.current is undefined, resulting in this error. Changing the function call from`.current(event)` to `.current.?(event)` will remove the error.

Fix "onCloseAutoFocus.current is not a function"

---

.changeset/eight-houses-take.md
docs/src/lib/components/demos/popover-demo.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-content-static.svelte
packages/bits-ui/src/lib/bits/popover/components/popover-content.svelte
packages/bits-ui/src/lib/bits/popover/popover.svelte.ts

This pull request addresses a bug in the `Popover` component to ensure proper handling of outside interactions when using a `customAnchor`.
* Updated the `PopoverContentState` class to add a null check for `closestTrigger` before comparing it with `this.root.triggerNode`, ensuring proper behavior when interacting outside the popover.

fix(Popover): custom anchor outside interaction handling

---

.changeset/poor-comics-help.md
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-content-static.svelte
packages/bits-ui/src/lib/bits/link-preview/components/link-preview-content.svelte

fix(LinkPreview): ensure grace area exists when `forceMount=true`

---

docs/src/lib/content/api-reference/context-menu.api.ts
docs/src/lib/content/api-reference/dropdown-menu.api.ts
docs/src/lib/content/api-reference/menu.api.ts
docs/src/lib/content/api-reference/menubar.api.ts

fixes #1718 
The API Reference docs for the menubar, context menu, and dropdown menu components were inheriting incorrect data attributes from the parent menu. Removed the definitions from the menu and added the correct attributes to each components reference.

docs: Fix menu data attributes in API Reference

---

.changeset/cruel-cities-know.md
.changeset/good-parrots-greet.md
.gitignore
package.json
packages/bits-ui/src/lib/bits/select/select.svelte.ts
tests/src/tests/combobox/combobox.browser.test.ts

- Recompute whether or not the `Combobox.ScrollDown` button should render when the input value changes, as the list may have shrunk/expanded
- Don't set the value of the deselected item to the `Combobox.Input` when `type="multiple"`

fix(Combobox): a few issues
